const {test}=require('node:test'),assert=require('node:assert/strict');
const {NetworkTools}=require('../src/network.cjs');const {ApiAdapter}=require('../src/adapters/api.cjs');
test('general web research is searched and delivered back to model with citation',async()=>{
 let modelCalls=0,query,received;const network=new NetworkTools({getSearchKey:()=> 'search-secret',fetchImpl:async(url,opts)=>{query=JSON.parse(opts.body).query;return Response.json({results:[{title:'Official material',url:'https://example.org/research',content:'Research evidence, unrelated to weather.'}]});}});
 const api=new ApiAdapter({getKey:()=> 'model-secret',network,isNetworkEnabled:()=>true,fetchImpl:async(url,opts)=>{const b=JSON.parse(opts.body);assert.ok(!opts.body.includes('search-secret'));modelCalls++;if(modelCalls===1)return Response.json({choices:[{message:{role:'assistant',content:null,tool_calls:[{id:'research',type:'function',function:{name:'web_search',arguments:JSON.stringify({query:'新材料研究进展'})}}]}}]});received=b.messages.at(-1).content;return Response.json({choices:[{message:{role:'assistant',content:'根据查到的资料进行分析。'}}]});}});
 const result=await api.send({member:{id:'a',baseUrl:'https://example.org/v1',format:'openai',model:'fixture'},prompt:'搜索新材料研究进展',signal:new AbortController().signal});assert.equal(query,'新材料研究进展');assert.match(received,/Research evidence/);assert.match(result.text,/https:\/\/example.org\/research/);
});
test('API calls weather then receives real tool result and source without search credentials',async()=>{
 const requests=[];const network=new NetworkTools({fetchImpl:async url=>url.includes('geocoding')?Response.json({results:[{name:'北京',latitude:39.9,longitude:116.4,country:'中国'}]}):Response.json({current:{temperature_2m:22}})});
 const api=new ApiAdapter({getKey:()=> 'test',network,isNetworkEnabled:()=>true,fetchImpl:async(url,opts)=>{const b=JSON.parse(opts.body);requests.push(b);return Response.json({choices:[{message:requests.length===1?{role:'assistant',content:null,tool_calls:[{id:'one',type:'function',function:{name:'weather',arguments:'{"city":"Beijing"}'}}]}:{role:'assistant',content:'北京气温22℃。'}}]});}});
 const result=await api.send({member:{id:'test',baseUrl:'https://example.com/v1',format:'openai',model:'test'},prompt:'北京天气',signal:new AbortController().signal});
 assert.match(result.text,/api.open-meteo.com/);assert.equal(requests.length,2);assert.match(requests[1].messages.at(-1).content,/22/);assert.deepEqual(requests[0].tools.map(x=>x.function.name),['weather']);
});
test('search sends key only to fixed search endpoint; unsupported tools rejected',async()=>{let request;const network=new NetworkTools({getSearchKey:()=> 'private-test',fetchImpl:async(url,opts)=>{request={url,...opts};return Response.json({results:[{title:'Source',url:'https://example.com',content:'Evidence'}]});}});const s=new AbortController().signal;const r=await network.run('web_search',{query:'天气'},s);assert.equal(request.url,'https://api.tavily.com/search');assert.equal(request.headers.Authorization,'Bearer private-test');assert.ok(!JSON.stringify(r).includes('private-test'));await assert.rejects(()=>network.run('shell',{},s));});
