const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const location=require('../src/data-location.cjs'),{NetworkTools}=require('../src/network.cjs');
test('data relocation copies latest durable data, preserves source and refuses nonempty/overlapping targets',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'roundtable-location-')),source=path.join(root,'data'),dest=path.join(root,'destination');fs.mkdirSync(source);fs.mkdirSync(dest);fs.writeFileSync(path.join(source,'rooms.json'),'old');fs.mkdirSync(path.join(source,'attachments'));fs.writeFileSync(path.join(source,'attachments','a.txt'),'attachment');
 assert.throws(()=>location.schedule(root,source,source));assert.throws(()=>location.schedule(root,source,root));
 location.schedule(root,source,dest);fs.writeFileSync(path.join(source,'rooms.json'),'latest');assert.equal(location.resolve(root).path,fs.realpathSync(dest));assert.equal(fs.readFileSync(path.join(dest,'rooms.json'),'utf8'),'latest');assert.equal(fs.readFileSync(path.join(source,'rooms.json'),'utf8'),'latest');assert.equal(fs.readFileSync(path.join(dest,'attachments','a.txt'),'utf8'),'attachment');assert.equal(location.resolve(root).path,fs.realpathSync(dest));assert.throws(()=>location.schedule(root,source,dest));
 const other=path.join(root,'other');fs.mkdirSync(other);location.schedule(root,source,other);fs.writeFileSync(path.join(other,'new-user-file'),'keep');assert.equal(location.resolve(root).path,source);assert.equal(fs.readFileSync(path.join(other,'new-user-file'),'utf8'),'keep');fs.rmSync(root,{recursive:true});
});
test('SearXNG sends a query without Tavily credentials and surfaces disabled JSON',async()=>{
 const controller=new AbortController();let url,options;const tools=new NetworkTools({getSearchConfig:()=>({provider:'searxng',url:'https://search.example/base'}),getSearchKey:()=>{throw Error('must not read Tavily key');},fetchImpl:async(u,o)=>{url=new URL(u);options=o;return new Response(JSON.stringify({results:[{title:'Source',url:'https://example.org',content:'Evidence'}]}));}});
 assert.ok(tools.definitions().some(t=>t.function.name==='web_search'));const r=await tools.run('web_search',{query:'中文资料 & facts'},controller.signal);assert.equal(url.pathname,'/base/search');assert.equal(url.searchParams.get('q'),'中文资料 & facts');assert.equal(url.searchParams.get('format'),'json');assert.equal(options.headers,undefined);assert.equal(r.results[0].content,'Evidence');tools.fetch=async()=>new Response('{}');await assert.rejects(()=>tools.run('web_search',{query:'x'},controller.signal),/JSON/);
});
