(()=>{
 const $=id=>document.getElementById(id),call=(n,a)=>window.roundtable.call(n,a),el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 let scope,files=[],selected,onChange,busy=false;
 const dialog=el('dialog');dialog.id='attachments-dialog';dialog.innerHTML='<div class="dialog-head"><div><div class="eyebrow">SHARED MATERIALS</div><h2>附件与共享资料</h2></div><button id="attachments-close">✕</button></div><p class="attachment-help">文件先保存在本机，运行时再发送给所选 AI。工作流中的附件会提供给每个 AI 节点。</p><div class="attachment-toolbar"><label>PDF 选页<input id="attachment-pages" value="1-5" placeholder="1-5 或 1,3,6-8"></label><button id="attachments-add" class="primary">＋ 添加文件</button><span>单文件 ≤25 MB · 最多 10 个附件 · PDF 每次最多 12 页</span></div><div class="attachment-layout"><div id="attachment-list"></div><div id="attachment-preview"><p>支持图片、PDF、DOCX、XLSX、PPTX 和文本。选择文件后查看实际提取结果。</p></div></div><details><summary>每位 AI 实际能收到什么？</summary><div id="attachment-deliveries"></div></details><p id="attachment-status" role="status"></p>';document.body.append(dialog);
 const status=t=>$('attachment-status').textContent=t;
 const action=fn=>async()=>{try{await fn();}catch(e){status(e.message);}};
 async function refresh(){files=await call('attachmentsList',{scope});render();const deliveries=await call('attachmentsDelivery',{scope});$('attachment-deliveries').replaceChildren();for(const d of deliveries){const p=el('p');p.append(el('strong',d.name),el('span','\n'+(d.description||'尚未添加附件')));$('attachment-deliveries').append(p);}await onChange?.(files);}
 function render(){const area=$('attachment-list');area.replaceChildren();for(const a of files){const b=el('button');b.className=a.id===selected?'selected':'';b.append(el('strong',a.name),el('small',a.details),el('small',a.visualCount?`${a.visualCount} 张图像 / 页面图 + ${a.text.length} 字文字`:`提取文字 ${a.text.length} 字`));b.onclick=()=>{selected=a.id;render();};area.append(b);}preview();}
 function preview(){const area=$('attachment-preview');area.replaceChildren();const a=files.find(a=>a.id===selected);if(!a){area.append(el('p','点击左侧附件预览文字、检查警告或移除文件。'));return;}area.append(el('h3',a.name),el('p',a.details));for(const warning of a.warnings||[]){const p=el('p',warning);p.className='attachment-warning';area.append(p);}if(a.visualCount){const image=el('img');image.id='attachment-image-preview';image.alt='附件图像预览';const pages=el('select');for(let i=0;i<a.visualCount;i++){const o=el('option',a.imagePages?.[i]?'第 '+a.imagePages[i]+' 页':'图像 '+(i+1));o.value=i;pages.append(o);}const show=async()=>{try{const data=await call('attachmentPreview',{id:a.id,index:Number(pages.value)});if(selected===a.id)image.src=data;}catch(e){status(e.message);}};pages.onchange=show;area.append(pages,image);show();}const textarea=el('textarea');textarea.id='attachment-excerpt';textarea.value=a.text;textarea.rows=8;textarea.maxLength=20000;textarea.placeholder='没有文字层。图像将发送给 Codex 或已启用图像输入的 API；其他成员无法直接看图。';area.append(textarea);const buttons=el('div');buttons.className='form-actions';const save=el('button','保存文字节选'),reveal=el('button','在文件夹中显示'),remove=el('button','移除附件');save.onclick=action(async()=>{await call('attachmentsEdit',{scope,id:a.id,text:textarea.value});await refresh();status('已更新文字节选。');});reveal.onclick=action(()=>call('attachmentReveal',{id:a.id}));remove.onclick=action(async()=>{await call('attachmentsRemove',{scope,id:a.id});selected=null;await refresh();});buttons.append(save,reveal,remove);area.append(buttons);}
 $('attachments-add').onclick=action(async()=>{if(busy)return;busy=true;$('attachments-add').disabled=true;$('attachments-close').disabled=true;status('正在选择文件并在本机解析…');try{const r=await call('attachmentsImport',{scope,pages:$('attachment-pages').value});selected=r.files.at(-1)?.id;await refresh();status(r.errors.length?r.errors.join('\n'):'导入完成。请核对文字节选、PDF 页码和成员接收范围。');}finally{busy=false;$('attachments-add').disabled=false;$('attachments-close').disabled=false;}});
 $('attachments-close').onclick=()=>dialog.close();dialog.oncancel=e=>{if(busy)e.preventDefault();};
 window.attachmentUI={open:async(s,cb)=>{scope=s;onChange=cb;selected=null;status('');await refresh();if(!dialog.open)dialog.showModal();}};
 $('attach').textContent='＋ 附件 / 资料';
 // API image support is explicitly configurable; text-only remains the default.
 const option=el('label');option.className='inline';const check=el('input');check.type='checkbox';check.id='member-vision';option.append(check,document.createTextNode('此 API 模型支持图像输入（发送图片 / PDF 页面图）'));$('member-format').closest('[data-kind]').append(option,el('p','请以所选模型的实际能力为准；未开启时只发送提取文字。'));
 // The manual web relay never manipulates the website or its upload controls.
 const box=el('div');box.id='manual-files';$('manual-status').before(box);
 let last='';setInterval(async()=>{try{const job=await call('manualStatus'),key=job?.id||'';if(key===last)return;last=key;box.replaceChildren();if(!job?.manualFiles?.length)return;box.append(el('p','这些附件需要你在原网页手动上传：'));for(const a of job.manualFiles){const b=el('button',a.name+' ↗');b.onclick=action(()=>call('attachmentReveal',{id:a.id}));box.append(b);}const l=el('label');l.className='inline';const c=el('input');c.type='checkbox';c.id='manual-files-uploaded';l.append(c,document.createTextNode('我已在原网页上传这些附件，再粘贴下面的回复'));box.append(l);}catch{}},600);
})();
