(()=>{
const call=(name,args)=>window.roundtable.call(name,args),make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
window.dutyOptions=(area,n,prompt,presets,changed,active)=>{
 const panel=make('div');panel.className='duty-options';const controls=make('div');controls.className='duty-controls';controls.append(make('span','快捷职责'));const manage=make('button','管理快捷职责');manage.type='button';manage.disabled=active;controls.append(manage);const chips=make('div');chips.className='duty-chips';panel.append(controls,chips);prompt.closest('label').before(panel);let items=[];
 const sync=()=>{for(const b of chips.children){const t=items.find(t=>t.id===b.dataset.id),on=t&&prompt.value.includes(t.content);b.classList.toggle('selected',!!on);b.setAttribute('aria-pressed',String(!!on));}};
 const commit=()=>{n.instruction=prompt.value;n.duty=items.filter(t=>prompt.value.includes(t.content)).map(t=>t.name).join(' · ')||(prompt.value?'自定义':'');delete n.dutyMode;changed();sync();};
 async function refresh(){items=n.type==='execute'?[{id:'execute',name:'执行',content:presets.执行},...(await call('roleTemplates')).filter(t=>!t.builtin||t.id==='builtin_local_verify')]:await call('roleTemplates');if(!panel.isConnected)return;chips.replaceChildren();for(const t of items){const b=make('button',t.name);b.type='button';b.dataset.id=t.id;if(!t.builtin)b.dataset.userContent='true';b.dataset.duty=t.name;b.disabled=active;b.title=t.content;b.onclick=()=>{prompt.value=prompt.value.includes(t.content)?prompt.value.replace(t.content,'').replace(/\n{3,}/g,'\n\n').trim():[prompt.value.trim(),t.content].filter(Boolean).join('\n\n');commit();};chips.append(b);}sync();}
 manage.onclick=()=>window.dutyLibrary.open();const update=()=>{if(panel.isConnected)refresh().catch(console.error);else document.removeEventListener('duties-updated',update);};document.addEventListener('duties-updated',update);prompt.addEventListener('input',sync);prompt.addEventListener('change',commit);refresh().catch(console.error);
};
const d=make('dialog');d.id='duty-library';d.innerHTML='<div class="dialog-head"><h2>管理快捷职责</h2><button id="duty-close">关闭</button></div><div id="duty-library-list"></div><label>名称<input id="duty-name" maxlength="60"></label><label>职责内容<textarea id="duty-content" rows="5"></textarea></label><div class="duty-library-actions"><button id="duty-new">新建</button><button id="duty-delete">删除</button><button id="duty-save" class="primary">保存快捷职责</button></div><p id="duty-status" role="status"></p>';document.body.append(d);const $=id=>document.getElementById(id);let selected=null;
async function list(){const items=await call('roleTemplates');$('duty-library-list').replaceChildren();for(const t of items){const b=make('button',t.name);b.onclick=()=>{selected=t;$('duty-name').value=t.name;$('duty-content').value=t.content;$('duty-delete').disabled=t.builtin;$('duty-status').textContent=t.builtin?'内置职责修改后保存为新的快捷职责。':'';};$('duty-library-list').append(b);}}
const clear=()=>{selected=null;$('duty-name').value='';$('duty-content').value='';$('duty-delete').disabled=true;$('duty-status').textContent='';};$('duty-new').onclick=clear;$('duty-close').onclick=()=>d.close();
$('duty-save').onclick=async()=>{try{await call('roleTemplateSave',{template:{id:selected&&!selected.builtin?selected.id:undefined,name:$('duty-name').value,content:$('duty-content').value}});await list();clear();$('duty-status').textContent='已保存';document.dispatchEvent(new Event('duties-updated'));window.roleUI?.sync();}catch(e){$('duty-status').textContent=e.message;}};
$('duty-delete').onclick=async()=>{try{if(selected&&await call('roleTemplateDelete',{id:selected.id})){await list();clear();document.dispatchEvent(new Event('duties-updated'));window.roleUI?.sync();}}catch(e){$('duty-status').textContent=e.message;}};
window.dutyLibrary={open:async()=>{clear();await list();d.showModal();}};
})();
