(()=>{
 const $=id=>document.getElementById(id),make=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
 const home=make('section');home.id='home-view';home.innerHTML='<div class="eyebrow">同桌 AI</div><h1>让 AI 一起完成任务</h1><p>首次使用：管理 AI → 选择讨论方式 → 发起任务。</p><div class="home-cards"><button id="home-members"><strong>1　管理 AI</strong><span>选择服务商，连接你的成员</span></button><button id="home-chat"><strong>2　讨论室</strong><span>选择两位或更多 AI，直接开始聊天</span></button><button id="home-workflow"><strong>3　工作流</strong><span>使用内置工作流，或自己搭建流程</span></button></div><p class="help">已有讨论可从左侧打开。切换页面会保留当前画布和输入。</p>';
 document.body.append(home);
 function openHome(){document.querySelector('main').hidden=true;$('workflow').hidden=true;$('workflow-nav').classList.remove('active');home.hidden=false;}
 const nav=make('button','主页');nav.id='home-nav';nav.className='new-room';$('workflow-nav').before(nav);nav.onclick=openHome;
 const back=make('button','← 返回主页');back.id='wf-home';$('wf-members').before(back);back.onclick=openHome;
 $('home-members').onclick=()=>$('settings').click();$('home-chat').onclick=()=>$('discussion-nav').click();$('home-workflow').onclick=()=>$('workflow-nav').click();
 const edit=make('button','积木工具箱 · 展开');edit.id='wf-edit-mode';$('wf-members').before(edit);const palette=document.querySelector('.wf-palette');palette.hidden=true;$('workflow').classList.add('wf-simple');edit.onclick=()=>{palette.hidden=!palette.hidden;$('workflow').classList.toggle('wf-simple',palette.hidden);edit.textContent=palette.hidden?'积木工具箱 · 展开':'积木工具箱 · 收起';edit.setAttribute('aria-expanded',String(!palette.hidden));};
 const tools=make('div');tools.className='wf-navigation';document.querySelector('.wf-body').before(tools);tools.append(edit,make('span','拖入积木或点击添加 · 缩放'),$('wf-minus'),$('wf-scale'),$('wf-plus'),$('wf-overview'),$('wf-fit'));edit.setAttribute('aria-expanded','false');
 const check=make('label');check.className='inline';check.innerHTML='<input type="checkbox" id="member-execution">允许这个终端智能体担任本地执行者';$('member-args').parentElement.after(check);
 const hint=make('p','适用于提供标准输入/输出接口的 CLI 或适配脚本。仅选择桌面软件的 exe 通常无法对接；终端程序的权限与审批由其自身控制。');hint.className='help';check.after(hint);
 window.roundtable.call('appIcon').then(url=>{if(!url||url==='data:image/png;base64,')return;const img=make('img');img.src=url;img.alt='同桌 AI';img.width=42;img.height=42;const mark=document.querySelector('.brand-mark');mark.replaceChildren(img);mark.style.background='transparent';}).catch(()=>{});
 openHome();
 const netDialog=make('dialog');netDialog.innerHTML='<h2>联网能力</h2><p>为支持工具调用的 OpenAI 兼容 API 成员提供联网工具（如 DeepSeek、Kimi）。</p><label class="inline"><input type="checkbox" id="network-enabled">启用 API 联网工具</label><p class="help">天气：Open-Meteo，个人非商业使用无需密钥。请在问题里写明城市。<br>网页搜索：填写 Tavily 密钥后启用；查询词会发送到搜索服务，结果会交给 AI。<br>Claude 原生 API 与网页接力暂不使用这里的工具。</p><label>搜索服务<select id="search-provider"><option value="tavily">Tavily · 每月免费额度</option><option value="searxng">SearXNG · 自有 / 公共实例</option></select></label><label id="search-url-label">SearXNG 服务地址<input id="search-url" placeholder="https://your-searxng.example"></label><p class="help">Tavily 每月提供 1,000 免费额度；超额费用按官方规则。SearXNG 软件免费，需要可用实例且启用 JSON API，公共实例可能限制访问。查询词会发送给所选服务。</p><label>Tavily 搜索密钥<input type="password" id="network-key" autocomplete="off" placeholder="留空保留已有密钥"></label><label class="inline"><input type="checkbox" id="network-clear">清除已保存搜索密钥</label><p id="network-status" class="help"></p><div class="form-actions"><button id="network-docs">获取搜索密钥</button><button id="network-close">关闭</button><button id="network-save" class="primary">保存</button></div>';document.body.append(netDialog);
 const sideNet=make('button','联网设置');sideNet.className='text-btn';sideNet.id='sidebar-network';document.querySelector('.sidebar-footer').before(sideNet);
 const openNet=async()=>{try{const s=await window.roundtable.call('networkSettings');$('network-enabled').checked=s.enabled;$('search-provider').value=s.provider;$('search-url').value=s.url;$('search-url-label').hidden=s.provider!=='searxng';$('network-key').value='';$('network-clear').checked=false;$('network-status').textContent=s.provider==='searxng'?'已选择 SearXNG；请确认服务启用 JSON API。':s.hasKey?'已保存加密搜索密钥。':'未配置网页搜索密钥；仍可使用天气工具。';netDialog.showModal();}catch(e){alert(e.message);}};sideNet.onclick=openNet;
 $('search-provider').onchange=()=>{$('search-url-label').hidden=$('search-provider').value!=='searxng';};
 $('network-close').onclick=()=>netDialog.close();$('network-docs').onclick=()=>window.roundtable.call('networkDocs');$('network-save').onclick=async()=>{try{await window.roundtable.call('networkSave',{enabled:$('network-enabled').checked,provider:$('search-provider').value,url:$('search-url').value.trim(),key:$('network-key').value,clearKey:$('network-clear').checked});$('network-key').value='';netDialog.close();}catch(e){$('network-status').textContent=e.message;}};
})();
