(()=>{const make=(t,text)=>{const e=document.createElement(t);if(text!==undefined)e.textContent=text;return e;};
 const section=make('section');section.className='color-settings';section.innerHTML='<h3>配色</h3><div id="color-swatches"></div><label class="color-custom">自定义强调色<input id="accent-color" type="color" value="#0071e3"></label><button id="accent-reset" class="text-btn">恢复默认配色</button>';document.getElementById('ui-style').closest('label').after(section);
 const root=document.documentElement;const apply=color=>{if(!/^#[a-f0-9]{6}$/i.test(color)){root.removeAttribute('data-accent');root.style.removeProperty('--accent');root.style.removeProperty('--accent-text');document.getElementById('accent-color').value='#0071e3';return;}root.dataset.accent='custom';root.style.setProperty('--accent',color);const rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4),l=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];root.style.setProperty('--accent-text',l>.179?'#111827':'#ffffff');document.getElementById('accent-color').value=color;};
 for(const color of ['#0071e3','#6e56cf','#c03978','#16866e','#b36914','#566477']){const b=make('button');b.className='color-swatch';b.style.background=color;b.setAttribute('aria-label',color);b.onclick=()=>{localStorage.setItem('roundtable-accent',color);apply(color);};document.getElementById('color-swatches').append(b);}document.getElementById('accent-color').oninput=e=>{apply(e.target.value);localStorage.setItem('roundtable-accent',e.target.value);};document.getElementById('accent-reset').onclick=()=>{localStorage.removeItem('roundtable-accent');apply('');};apply(localStorage.getItem('roundtable-accent')||'');
 const more=make('details');more.className='workflow-more';more.append(make('summary','更多操作'));const actions=make('div');for(const id of ['wf-copy','wf-import','wf-export','wf-delete-all'])actions.append(document.getElementById(id));more.append(actions);document.getElementById('wf-check').after(more);
 // Native popups can be dismissed by renderer changes. Keep a modal snapshot instead.
 const popup=make('dialog');popup.id='choice-popup';popup.innerHTML='<div class="dialog-head"><h2>选择选项</h2><button id="choice-close">关闭</button></div><div id="choice-items"></div><p id="choice-status" role="status"></p>';document.body.append(popup);document.getElementById('choice-close').onclick=()=>popup.close();
 function open(select){if(select.disabled||select.multiple||select.size>1)return;const area=document.getElementById('choice-items');area.replaceChildren();document.getElementById('choice-status').textContent='';for(const option of select.options){const b=make('button',option.textContent);b.type='button';b.className='choice-item';b.dataset.value=option.value;b.setAttribute('aria-pressed',String(option.selected));b.disabled=option.disabled||option.parentElement.disabled===true;b.onclick=()=>{if(!select.isConnected||select.disabled){document.getElementById('choice-status').textContent='此设置已更新，请关闭后重新选择。';return;}select.value=option.value;select.dispatchEvent(new Event('input',{bubbles:true}));select.dispatchEvent(new Event('change',{bubbles:true}));popup.close();};area.append(b);}popup.showModal();}
 document.addEventListener('pointerdown',e=>{const s=e.target.closest('select');if(s&&!s.disabled&&!s.multiple&&s.size<=1){e.preventDefault();open(s);}},true);document.addEventListener('click',e=>{if(e.target.closest('select'))e.preventDefault();},true);document.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT'&&['Enter',' '].includes(e.key)){e.preventDefault();open(e.target);}},true);
})();
