(()=>{const make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};let catalog=[],collapsed=new Set(),palettes=new Set();
 const picker=make('dialog');picker.id='model-picker';picker.innerHTML='<div class="dialog-head"><h2>选择模型</h2><button id="model-picker-close">关闭</button></div><div id="model-role-choices"></div><div id="model-picker-tree"></div><button id="model-picker-manage" class="text-btn">管理模型列表</button>';document.body.append(picker);
 const manager=make('dialog');manager.id='model-manager';manager.innerHTML='<div class="dialog-head"><h2>模型列表</h2><button id="model-manager-close">关闭</button></div><label>服务商连接<select id="model-account"></select></label><p class="help">复用该连接的密钥和地址。接口返回的列表不保证每个模型都有调用权限；也可手动填写模型 ID，每行一个。</p><textarea id="model-inventory" rows="8" placeholder="每行一个模型 ID"></textarea><div class="form-actions"><button id="model-inventory-fetch">从接口读取</button><button id="model-inventory-save" class="primary">保存列表</button></div><p id="model-inventory-status" role="status"></p>';document.body.append(manager);
 function entries(c){return c.kind==='web'?[{model:'',label:'网页手动接力 · 在网站内选择模型'}]:[...(c.kind==='codex'?[{model:'',label:'沿用连接默认模型'}]:[]),...c.models.map(model=>({model,label:model}))];}
 function tree(target,onPick,execution=false){target.replaceChildren();const groups=new Map();for(const c of catalog.filter(c=>!execution||c.kind==='codex')){if(!groups.has(c.company))groups.set(c.company,[]);groups.get(c.company).push(c);}for(const [company,connections]of groups){const group=make('details');group.className='model-company';group.open=!collapsed.has(company);group.append(make('summary',company));group.ontoggle=()=>{group.open?collapsed.delete(company):collapsed.add(company);};for(const c of connections){const account=make('div');account.className='model-account';if(connections.length>1)account.append(make('small',c.name));for(const item of entries(c)){const b=make('button',item.label);b.type='button';b.className='model-leaf';b.dataset.memberId=c.memberId;b.dataset.model=item.model;if(!item.model)b.dataset.uiText='true';b.title=c.name+' / '+item.label;b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('application/roundtable',JSON.stringify({memberId:c.memberId,model:item.model}));b.onclick=()=>onPick?.({memberId:c.memberId,model:item.model});account.append(b);}if(!entries(c).length)account.append(make('small','尚无模型，请读取或手动添加'));group.append(account);}target.append(group);}if(!groups.size)target.append(make('p','先在成员设置中添加服务商连接。'));}
 async function refresh(){catalog=await call('modelCatalog');for(const p of [...palettes]){if(!p.isConnected){palettes.delete(p);continue;}tree(p,null);}document.dispatchEvent(new Event('model-catalog-updated'));}
 function fill(){const c=catalog.find(c=>c.memberId===$('model-account').value);$('model-inventory').value=(c?.models||[]).join('\n');$('model-inventory-fetch').disabled=c?.kind!=='api';$('model-inventory-status').textContent='';}
 async function manage(id){try{await refresh();$('model-account').replaceChildren();for(const c of catalog.filter(c=>c.kind!=='web')){const o=make('option',c.company+' / '+c.name);o.value=c.memberId;$('model-account').append(o);}if(id)$('model-account').value=id;fill();manager.showModal();}catch(e){notify(e.message);}}
 $('model-account').onchange=fill;$('model-manager-close').onclick=()=>manager.close();$('model-picker-close').onclick=()=>picker.close();$('model-picker-manage').onclick=()=>manage();
 $('model-inventory-save').onclick=async()=>{try{await call('modelCatalogSave',{memberId:$('model-account').value,models:$('model-inventory').value.split('\n').map(s=>s.trim()).filter(Boolean)});await refresh();$('model-inventory-status').textContent='列表已保存，工作流可以选择这些模型。';}catch(e){$('model-inventory-status').textContent=e.message;}};
 $('model-inventory-fetch').onclick=async()=>{const button=$('model-inventory-fetch');button.disabled=true;$('model-inventory-status').textContent='正在读取…';try{const models=await call('modelCatalogFetch',{memberId:$('model-account').value});$('model-inventory').value=models.join('\n');$('model-inventory-status').textContent='已读取，请保存列表。';}catch(e){$('model-inventory-status').textContent=e.message;}finally{button.disabled=false;}};
 function attach(select,{getModel=()=>'',pick,execution=false}){const b=make('button');b.type='button';b.className='model-select-button';select.hidden=true;select.after(b);const sync=()=>{b.disabled=select.disabled;const option=select.selectedOptions[0];b.textContent=(option?.textContent||'选择公司 / 模型')+(getModel()?' / '+getModel():'')+' ▾';};sync();b.onclick=async()=>{try{await refresh();const roles=$('model-role-choices');roles.replaceChildren();for(const o of [...select.options].filter(o=>!o.value||o.value.startsWith('@'))){const role=make('button',o.textContent);role.onclick=()=>{select.value=o.value;select.dispatchEvent(new Event('change'));picker.close();};roles.append(role);}tree($('model-picker-tree'),choice=>{pick(choice);picker.close();},execution);picker.showModal();}catch(e){notify(e.message);}};}
 document.addEventListener('click',e=>{if(e.target.closest('#workflow-nav'))refresh().catch(()=>{});});
 window.modelTree={attach,manage,palette:target=>{palettes.add(target);tree(target,null);const tools=make('button','管理模型列表');tools.type='button';tools.className='model-manage';tools.onclick=()=>manage();if(!target.parentElement.querySelector('.model-manage'))target.before(tools);}};
 refresh().catch(e=>notify(e.message));const manageButton=make('button','管理可选模型');manageButton.type='button';manageButton.id='member-models-manage';manageButton.onclick=()=>manage($('member-id').value);$('member-model').closest('[data-kind]').append(manageButton);
})();

