(()=>{
 const make=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;},call=(n,a)=>window.roundtable.call(n,a);
 const dialog=make('dialog');dialog.id='preferences-dialog';dialog.innerHTML='<div class="dialog-head"><h2>软件设置</h2><button id="preferences-close">关闭</button></div><label>语言 / Language<select id="ui-language"><option value="zh">简体中文</option><option value="en">English</option></select></label><label>界面风格<select id="ui-style"><option value="minimal">简约</option><option value="glass">玻璃</option><option value="liquid">液体金属</option></select></label><p class="help">语言设置用于界面与设置项，不翻译聊天内容、自定义工作流或系统错误信息。</p><h3>数据保存位置</h3><p id="data-current"></p><button id="data-choose">选择空文件夹</button><p id="data-pending" role="status"></p><p class="help">下次启动时复制迁移聊天、成员配置、工作流和附件。原文件保留；请勿同时打开两个副本。外部执行目录保持原路径。</p>';document.body.append(dialog);
 const button=make('button','软件设置');button.id='preferences-open';button.className='text-btn';document.getElementById('sidebar-network').after(button);
 const lang=document.getElementById('ui-language'),style=document.getElementById('ui-style');lang.value=localStorage.getItem('roundtable-language')==='en'?'en':'zh';style.value=localStorage.getItem('roundtable-style')||'glass';if(!style.value)style.value='glass';
 style.onchange=()=>{document.documentElement.dataset.style=style.value;localStorage.setItem('roundtable-style',style.value);};style.onchange();
 const translations={
 '重试此积木':'Retry this block',
 '常用任务':'Quick tasks','管理常用任务':'Manage quick tasks','新增任务':'New task','任务名称':'Task name','任务内容':'Task content','删除任务':'Delete task','保存任务':'Save task','任务已保存':'Task saved','任务已删除':'Task deleted',
 '技能库设置':'Skill library settings',
 '工作流使用的 AI':'Workflow members','此工作流没有 AI 任务积木':'This workflow has no AI task blocks','填写服务商提供的模型标识；本地智能体可留空使用默认模型':'Enter the provider model ID; leave blank for the local agent default','选择已支持智能体的程序；留空尝试自动检测':'Choose a supported agent executable; leave blank to try auto-detection',
 '软件设置':'Settings','关闭':'Close','界面风格':'Visual style','简约':'Minimal','玻璃':'Glass','液体金属':'Liquid metal','数据保存位置':'Data location','选择空文件夹':'Choose an empty folder',
 '语言设置用于界面与设置项，不翻译聊天内容、自定义工作流或系统错误信息。':'Language applies to the interface and settings. Conversations, custom workflows and system errors are not translated.',
 '下次启动时复制迁移聊天、成员配置、工作流和附件。原文件保留；请勿同时打开两个副本。外部执行目录保持原路径。':'Chats, members, workflows and attachments will be copied on next launch. Original files are retained. Do not run two copies at once. External execution folders keep their paths.',
 '外观':'Appearance','跟随系统':'System','浅色':'Light','深色':'Dark','⌂　主页':'⌂ Home','← 返回主页':'← Home','工作流':'Workflows','讨论室':'Discussion','联网设置':'Web search settings',
 '联网能力':'Web access','启用 API 联网工具':'Enable API web tools','搜索服务':'Search provider','SearXNG 服务地址':'SearXNG base URL','Tavily 搜索密钥':'Tavily API key','清除已保存搜索密钥':'Clear saved search key','获取搜索密钥':'Get search key','保存':'Save',
 '为支持工具调用的 OpenAI 兼容 API 成员提供联网工具（如 DeepSeek、Kimi）。':'Web tools for OpenAI-compatible API members that support tool calling, such as DeepSeek and Kimi.',
 'Tavily · 每月免费额度':'Tavily · monthly free credits','SearXNG · 自有 / 公共实例':'SearXNG · own / public instance',
 'Tavily 每月提供 1,000 免费额度；超额费用按官方规则。SearXNG 软件免费，需要可用实例且启用 JSON API，公共实例可能限制访问。查询词会发送给所选服务。':'Tavily offers 1,000 free monthly credits; additional usage follows provider pricing. SearXNG is free software but requires an instance with JSON enabled; public instances may restrict access. Queries are sent to the selected provider.',
 '管理 AI':'Manage AI','成员名称':'Member name','接入方式':'Connection type','讨论职责':'Discussion role','服务商预设':'Provider preset','协议':'Protocol','API 密钥':'API key','模型名称':'Model name','可执行程序路径':'Executable path','选择…':'Browse…','保存成员':'Save member','移除成员':'Remove member','检查连接':'Check connection','Codex 登录':'Sign in to Codex','启动参数（JSON 数组）':'Launch arguments (JSON array)',
 'API 模型':'API model','本机 Codex':'Local Codex','网页接力':'Web relay','终端程序':'Terminal program','清除已保存密钥':'Clear saved key','接口地址（Base URL，预设会自动填写）':'Base URL (filled by provider preset)','读取模型列表':'Fetch models','获取模型列表':'Fetch models','打开官方文档 ↗':'Official documentation ↗',
 '积木工具箱 · 展开':'Block toolbox · Show','积木工具箱 · 收起':'Block toolbox · Hide','拖入积木或点击添加 · 缩放':'Drag or click to add blocks · Zoom','适应全部节点':'Fit all nodes','回到起点':'Back to origin','流程积木':'Blocks','拖入 AI':'Drag an AI','分析':'Analyze','规划':'Plan','检查':'Review','验收':'Verify','汇总':'Summarize','执行':'Execute','自定义':'Custom',
 '设计你的协作流程':'Design your workflow','管理 AI':'Manage AI','检查配置':'Validate','另存为新工作流':'Save as new workflow','导入':'Import','导出':'Export','删除全部工作流':'Delete all workflows','清空聊天记录':'Delete all chats','删除':'Delete','＋ 新建工作流':'＋ New workflow','共用角色设置':'Shared roles','选择一个节点':'Select a node','快捷职责 · 点击填入，可继续修改':'Role presets · click to fill, then edit','职责与输出要求':'Role and output instructions','由谁负责 · 只选一位 AI':'Assigned AI · choose one',
 '工作流试运行与附件（可选）':'Workflow test run & attachments (optional)','选择执行目录':'Choose execution folder','运行工作流 →':'Run workflow →','导出结果':'Export results','停止':'Stop','本对话的协作方式':'Collaboration mode','管理工作流':'Manage workflows','管理 AI':'Manage AI','连接网页':'Connect website',
 '让 AI 一起完成任务':'Let AI work together','首次使用：管理 AI → 选择讨论方式 → 发起任务。':'Get started: manage AI → choose a mode → start a task.','1　管理 AI':'1 Manage AI','2　讨论室':'2 Discussion','3　工作流':'3 Workflows','选择服务商，连接你的成员':'Choose providers and connect members','选择两位或更多 AI，直接开始聊天':'Choose two or more AI members and start chatting','使用内置工作流，或自己搭建流程':'Use a built-in workflow or build your own',
 '工作流名称':'Workflow name','我的工作流…':'My workflows…','运行记录…':'Run history…','留空保留已有密钥':'Leave blank to keep saved key','留空保留已保存密钥':'Leave blank to keep saved key','密钥由操作系统加密保存。更改 API 地址后需重新填写密钥。':'Keys are encrypted by the operating system. Re-enter the key when changing the API address.'
 };
 Object.assign(translations,{'＋ 新建讨论':'＋ New discussion','讨论记录':'Conversations','记录保存在本机':'Saved on this computer','打开目录 ↗':'Open folder ↗','让不同的智能，一起思考':'Different AI, thinking together','已有讨论可从左侧打开。切换页面会保留当前画布和输入。':'Open conversations from the sidebar. Switching pages preserves your workflow and input.','允许这个终端智能体担任本地执行者':'Allow this terminal agent to execute local tasks','使用本机 Codex 登录，创建独立会话。讨论节点只读；工作流执行节点在你确认后可修改指定目录中的文件。':'Uses local Codex sign-in to create a separate session. Discussion nodes are read-only; execution nodes can change files in the selected folder after your confirmation.','适用于提供标准输入/输出接口的 CLI 或适配脚本。仅选择桌面软件的 exe 通常无法对接；终端程序的权限与审批由其自身控制。':'Requires a CLI or adapter with standard input/output. Selecting a desktop executable alone usually does not work. Permissions and approvals are controlled by the terminal agent.','程序从标准输入读取完整提示词，输出回答到标准输出，成功后退出（代码 0）。请只配置你信任的程序。':'The program reads the prompt from stdin, writes its reply to stdout, and exits with code 0 on success. Configure only programs you trust.'});
 Object.assign(translations,{'接收连接':'Connect here','连接下一步':'Connect next','连线方法：① 点击上游积木「连接下一步」 → ② 点击目标积木「接收连接」。按 Esc 取消。':'Connect blocks: ① Click “Connect next” on the first block → ② Click “Connect here” on the target. Esc cancels.','下一步：点击目标积木的「接收连接」。按 Esc 取消。':'Next: click “Connect here” on the target block. Esc cancels.','第一步：点击上游积木的「连接下一步」，再点这里。':'First click “Connect next” on the upstream block, then click here.','已取消连接。':'Connection cancelled.'});
 Object.assign(translations,{'管理连接':'Manage connections','删除连接':'Delete connection','这个积木还没有连接。':'This block has no connections yet.','连线：先点「连接下一步」，再点「接收连接」。删除：选中积木 → 右侧「管理连接」。Esc 取消连线。':'Connect: click “Connect next”, then “Connect here”. Delete: select a block → “Manage connections” on the right. Esc cancels connecting.','粘贴浏览器地址栏中的完整聊天网址':'Paste the full chat URL from your browser address bar','高级：自动网页桥（需许可、扩展和适配）':'Advanced: automated web bridge (permission, extension and adapter required)','打开 AI 的聊天页面，直接复制浏览器地址栏粘贴到这里即可，网址中的 ? 参数和 # 页面位置可以保留。请不要复制搜索结果页或 API 控制台地址。':'Open the AI chat page and paste its full address here. Query parameters (?) and fragments (#) are supported. Do not use a search results page or an API dashboard URL.','第一次使用请选择“手动接力”：无需扩展，程序整理讨论内容，你到原网页发送并交回回复。仅填写网址不会自动控制网页。':'For your first connection, choose manual relay: no extension needed. The app prepares the conversation; you send it on the website and paste the reply back. A URL alone does not enable browser automation.'});
 Object.assign(translations,{'插件管理':'Plugins','网页自动连接':'Automatic web connection','停用':'Disable','启用':'Enable','卸载':'Uninstall','重新安装':'Reinstall','已启用':'Enabled','已停用':'Disabled','已卸载':'Uninstalled','网页连接向导':'Web connection wizard','连接 AI 网页':'Connect an AI website','打开登录窗口':'Open sign-in window','发送测试消息':'Send test message','点选输入框':'Pick input box','点选发送按钮':'Pick send button','点选 AI 回复区域':'Pick AI reply','点选停止按钮（可选）':'Pick stop button (optional)','自动连接通道':'Automatic connection method','内置登录窗口（推荐）':'Built-in window (recommended)','浏览器扩展（旧方式）':'Browser extension (legacy)','我已确认该网站允许此自动接入方式':'I have confirmed this website permits this automation'});
 Object.assign(translations,{'自动识别网页控件':'Detect website controls','② 登录后先点“自动识别”。无法识别的部分再点选；如果没有已有回复，请先在网页中完成一次普通对话。配置保存后可复用。':'② After signing in, detect controls automatically. Pick any missing controls manually. If there is no reply yet, complete one conversation on the website first. Saved mappings can be reused.'});
 Object.assign(translations,{'Skill 技能库':'Skill library','新建技能':'New skill','新建':'New','导入 MD / TXT':'Import MD / TXT','分析技能示例':'Analysis example','技能名称':'Skill name','技能正文':'Skill instructions','启用技能':'Enable skill','使用范围':'Access scope','所有成员可用（黑名单优先）':'All members (deny list takes precedence)','仅允许勾选的成员':'Only selected members','删除技能':'Delete skill','保存技能':'Save skill','节点技能':'Node skills','继承成员默认技能':'Inherit member defaults','指定技能':'Select skills','不使用技能':'No skills','请先在技能库创建技能。':'Create a skill in the library first.','网页手动接力':'Manual web relay','终端程序（暂不开放）':'Terminal agent (unavailable)','自动网页接入（暂不开放）':'Web automation (unavailable)','当前开放 API、Codex 和网页手动接力。已有自动网页／终端配置保留，但运行前需切换接入方式。':'API, Codex and manual web relay are available. Existing web automation and terminal settings are retained; change their connection type before running.'});
 Object.assign(translations,{'本地智能体':'Local agent','智能体类型':'Agent type','Codex（已支持）':'Codex (supported)','选择协作方式':'Choose collaboration mode','职责模板':'Role templates','留空 / 自行填写':'Blank / custom instructions','自定义模板名称':'Custom template name','保存模板':'Save template','删除模板':'Delete template','职责模板 · 与管理 AI共用':'Role templates · shared with Manage AI','自定义 / 继承成员职责':'Custom / inherit member role','自由讨论':'Free discussion','按所选成员顺序交流':'Discuss in selected member order','正在读取工作流…':'Loading workflows…','可留空，按本次任务作答；也可以从下方选择职责模板':'Leave blank to follow the task, or select a role template below'});
 Object.assign(translations,{'配色':'Colors','自定义强调色':'Custom accent color','恢复默认配色':'Reset colors','选择选项':'Choose an option','多选':'Multiple','单选':'Single','清除已选':'Clear selected','更多操作':'More actions','工作流使用帮助':'Workflow help','此设置已更新，请关闭后重新选择。':'This setting has changed. Close and choose again.'});
 Object.assign(translations,{'快捷职责':'Quick roles','管理快捷职责':'Manage quick roles','职责内容':'Role instructions','保存快捷职责':'Save quick role','内置职责修改后保存为新的快捷职责。':'Changes to built-in roles are saved as a new quick role.'});
 Object.assign(translations,{'字体':'Fonts','界面字体':'Interface font','系统默认':'System default','微软雅黑':'Microsoft YaHei','等线':'DengXian','宋体':'SimSun','楷体':'KaiTi','文字大小':'Text size','较小 · 90%':'Small · 90%','标准 · 100%':'Standard · 100%','较大 · 110%':'Larger · 110%','大 · 120%':'Large · 120%','特大 · 130%':'Extra large · 130%','恢复默认字体':'Reset fonts','一起思考，让想法更清晰。Aa 012345':'Think together. Make ideas clearer. Aa 012345','背景配色':'Background colors','自定义背景色':'Custom background color','恢复主题背景':'Reset theme background','编写代码':'Write code','本地验证':'Local verification'});
 Object.assign(translations,{'使用方式':'Mode','单 AI':'Single AI','模型':'Model','上下文':'Context','接续当前对话':'Continue conversation','仅本次输入':'Current input only','自定义范围':'Custom scope','选择历史与资料':'Choose history & files','资料预览':'Preview materials','使用所选内容':'Use selected content','接续与资料':'History & materials','本对话附件':'Conversation attachments','此前工作流的附件':'Previous workflow attachments','查看当前历史上下文':'Preview history context','暂无对话附件':'No conversation attachments','没有待加入的附件':'No additional attachments','这里是当前历史的预览；新消息和节点职责会在运行时加入。图片读取取决于模型能力。本地生成文件不会自动发送，请通过聊天附件入口添加。':'This previews existing context. New input and node instructions are added when running. Image support depends on the model. Add local output files through attachments to share them.'});
 Object.assign(translations,window.englishCatalog||{});
 Object.assign(translations,{'独立验收':'Independent verification','语言 / Language':'Language','＋ 添加成员':'＋ Add member','网页地址':'Website URL','网页参与方式':'Website participation','双 AI 协作':'Two-AI collaboration','分工流水线':'Role pipeline','网页接力 · 手动接力':'Web relay · manual','本机智能体 · 可检查连接':'Local agent · connection check available','API 模型 · 待配置':'API model · not configured','API 模型 · 已配置':'API model · configured','成员职责是默认值，可留空。工作流积木填写了职责时，使用积木职责；留空则继承成员职责。Skill 提供额外方法，不替代本次任务。':'Member instructions are optional defaults. Block instructions override them. Skills supply methods, not a replacement task.','Claude Pro 使用手动接力：程序整理上下文，由你在原网页发送并粘贴回复。Claude 消费者条款限制未经许可的自动化访问；低频操作或逐次确认也不保证安全。':'Claude Pro uses manual relay: send the prepared context on the website and paste back the reply. Its consumer terms restrict unauthorized automated access; low frequency or per-action confirmation does not remove that restriction.'});
 Object.assign(translations,{'主页':'Home','默认模型（积木可单独选择其他模型）':'Default model (blocks can choose another model)','请以所选模型的实际能力为准；未开启时只发送提取文字。':'Image delivery depends on the selected model’s verified capabilities.','图像发送取决于具体模型能力；待确认状态不代表不支持。':'Image delivery depends on the model; unconfirmed does not mean unsupported.','这里选择能执行任务的本地程序，不是模型品牌。目前仅适配 Codex；其他智能体需接入其实际通信协议，不能只填写模型名或桌面 exe。':'Choose a supported local executor. Currently only Codex is adapted; other agents require a compatible communication protocol. A model name or desktop executable alone is insufficient.','天气：Open-Meteo，个人非商业使用无需密钥。请在问题里写明城市。':'Weather: Open-Meteo; no key for personal non-commercial use. Include the city in your question.','网页搜索：填写 Tavily 密钥后启用；查询词会发送到搜索服务，结果会交给 AI。':'Web search: configure a Tavily key. Queries go to the search service and results go to the AI.','Claude 原生 API 与网页接力暂不使用这里的工具。':'Native Claude API and web relay do not use these tools.'});
 Object.assign(translations,{'此接入暂不开放，请在“管理 AI”中修改接入方式':'This connection is unavailable. Change its connection type in Manage AI.'});
 const textOrigins=new WeakMap();
 const reverse=Object.fromEntries(Object.entries(translations).map(([a,b])=>[b,a]));
 function translate(){
  const en=lang.value==='en';document.documentElement.lang=en?'en':'zh-CN';
  const walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
  while(node=walk.nextNode()){
   if(!node.parentElement.closest('[data-ui-text],#members small,#rooms small,#messages .welcome h2,#messages #quick-manage,.wf-node-type,.wf-status,.wf-ports,.wf-duty,.model-manage,.model-company>summary')&&node.parentElement.closest('script,style,textarea,[data-user-content],#context-items,#handoff-context,#handoff-files,#messages,#rooms,#members,#skill-members,#skills-list,#room-list,.workflow-card-open,#wf-saved,#wf-history,#wf-ai-list,#member-list,#data-current,#data-pending,.wf-node strong,.wf-binding,#room-title'))continue;
   const raw=node.textContent,key=raw.trim();const prior=textOrigins.get(node);if(!en&&prior&&raw===prior.translated){node.textContent=prior.original;continue;}let value=en?translations[key]:reverse[key];if(en&&!value){if(/^\d+ 条回复$/.test(key))value=key.replace(' 条回复',' replies');else if(/^最多 \d+ 次回复$/.test(key))value=key.replace('最多 ','Up to ').replace(' 次回复',' replies');else if(/^\d+ 个积木 · /.test(key))value=key.replace(' 个积木 · 内置工作流',' blocks · built-in').replace(' 个积木 · 已保存',' blocks · saved');else if(key.startsWith('沿用 ')&&key.endsWith(' ▾'))value='Use '+(translations[key.slice(3,-2)]||key.slice(3,-2))+' ▾';else if(key.includes(' → '))value=key.split(' → ').map(x=>translations[x]||x).join(' → ');}if(!value&&en&&/^[＋+] /.test(key)&&translations[key.slice(2)])value=key.slice(0,2)+translations[key.slice(2)];if(value&&value!==key){const next=raw.replace(key,value);if(en)textOrigins.set(node,{original:raw,translated:next});node.textContent=next;}
  }
  for(const e of document.querySelectorAll('[placeholder],[title],[aria-label]'))for(const attr of ['placeholder','title','aria-label']){const old=e.getAttribute(attr),value=en?translations[old]:reverse[old];if(value)e.setAttribute(attr,value);}
 }
 let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;translate();});}).observe(document.body,{childList:true,subtree:true,characterData:true});
 const native=()=>{document.title=lang.value==='en'?'AI Roundtable · Discussion':'同桌 AI · 讨论室';call('nativeLanguage',{language:lang.value}).catch(e=>console.error(e));};lang.onchange=()=>{localStorage.setItem('roundtable-language',lang.value);translate();native();};translate();native();
 function location(s){document.getElementById('data-current').textContent=s.current;document.getElementById('data-pending').textContent=s.pending?(lang.value==='en'?'After restart: ':'重启后迁移到：')+s.pending:'';}
 button.onclick=async()=>{try{location(await call('dataLocation'));dialog.showModal();}catch(e){alert(e.message);}};
 document.getElementById('preferences-close').onclick=()=>dialog.close();document.getElementById('data-choose').onclick=async()=>{try{location(await call('dataLocationChoose'));}catch(e){document.getElementById('data-pending').textContent=e.message;}};
})();
