(async()=>{
 const $=id=>document.getElementById(id),el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const presets=await window.roundtable.call('providerCatalog');
 const parent=$('member-format').closest('[data-kind]'),label=el('label','服务商预设'),select=el('select');select.id='api-provider';const custom=el('option','自定义 / 第三方中转');custom.value='';select.append(custom);for(const [id,p]of Object.entries(presets)){const option=el('option',p.name);option.value=id;select.append(option);}label.append(select);parent.prepend(label);
 const help=el('p','API 密钥是通行证；接口地址（URL）是请求目的地；模型名称决定调用哪个 AI。选择官方服务商会自动填写地址。第三方中转请填写它自己的接口地址，不要填写聊天网页的网址。');help.className='help';label.after(help);
 const docs=el('button','官方文档 / 密钥申请指引');docs.type='button';docs.hidden=true;help.after(docs);docs.onclick=()=>window.roundtable.call('providerDocs',{id:select.value}).catch(e=>{$('form-status').textContent=e.message;});
 const providerNote=el('p');providerNote.className='help';docs.after(providerNote);
 function info(){const p=presets[select.value];docs.hidden=!p;providerNote.textContent=p?(p.note||'使用该服务商的 API 密钥。模型列表以您账号实际可用的模型为准；视觉能力请按选定模型确认。'):'';}
 const baseLabel=$('member-base').parentElement;for(const node of baseLabel.childNodes)if(node.nodeType===Node.TEXT_NODE)node.textContent='接口地址（Base URL，预设会自动填写）';
 const note=el('p','填写基础地址即可，不要在末尾添加 /chat/completions 或 /messages。模型名可通过下面的按钮读取，也可照提供商文档填写。');note.className='help';baseLabel.after(note);
 const row=el('div');row.className='form-row';const fetchButton=el('button','读取可用模型');fetchButton.id='fetch-models';fetchButton.type='button';const choices=el('select');choices.id='api-model-list';choices.setAttribute('aria-label','可用模型列表');const first=el('option','先填密钥，再读取模型');first.value='';choices.append(first);row.append(fetchButton,choices);$('member-model').parentElement.after(row);row.dataset.kind='api';
 select.onchange=()=>{info();const p=presets[select.value];if(!p)return;if($('member-base').value.trim()!==p.base)$('member-key').value='';$('member-base').value=p.base;$('member-format').value=p.format;$('member-model').value=p.model;$('member-vision').checked=p.vision;if($('member-name').value==='新的成员')$('member-name').value=p.name;fillModels([]);loadSavedModels();$('form-status').textContent='已填写接口地址，请填该服务商的密钥并确认模型。修改尚未保存。';};
 let catalogRequest=0;
 function fillModels(models){const value=$('member-model').value;choices.replaceChildren();$('model-options').replaceChildren();const placeholder=el('option',models.length?'选择默认模型':'暂无已保存模型，可读取或手动填写');placeholder.value='';choices.append(placeholder);for(const name of [...new Set(models)]){const o=el('option',name);o.value=name;choices.append(o);const hint=el('option');hint.value=name;$('model-options').append(hint);}choices.value=models.includes(value)?value:'';}
 async function loadSavedModels(){const request=++catalogRequest,id=$('member-id').value,base=$('member-base').value.trim(),format=$('member-format').value;try{const list=await window.roundtable.call('modelCatalog');if(request!==catalogRequest||id!==$('member-id').value||base!==$('member-base').value.trim()||format!==$('member-format').value)return;const entry=list.find(c=>c.memberId===id&&c.baseUrl.replace(/\/$/,'')===base.replace(/\/$/,'')&&c.format===format);fillModels(entry?.models||[]);}catch{if(request===catalogRequest)fillModels([]);}}
 document.addEventListener('model-catalog-updated',loadSavedModels);$('member-base').addEventListener('change',loadSavedModels);$('member-format').addEventListener('change',loadSavedModels);$('member-model').addEventListener('input',()=>{choices.value=[...choices.options].some(o=>o.value===$('member-model').value)?$('member-model').value:'';});
 choices.onchange=()=>{if(choices.value)$('member-model').value=choices.value;};
 fetchButton.onclick=async()=>{fetchButton.disabled=true;$('form-status').textContent='正在向所填接口读取模型列表…';try{const models=await window.roundtable.call('discoverModels',{member:{id:$('member-id').value,name:$('member-name').value||'API',kind:'api',role:$('member-role').value,baseUrl:$('member-base').value.trim(),format:$('member-format').value},key:$('member-key').value});choices.replaceChildren();const first=el('option','选择一个模型');first.value='';choices.append(first);for(const name of models){const option=el('option',name);option.value=name;choices.append(option);}$('form-status').textContent=models.length?`读取到 ${models.length} 个模型，请选择后保存。`:'接口没有返回模型列表，请按提供商文档填写模型名。';}catch(e){$('form-status').textContent=e.message;}finally{fetchButton.disabled=false;}};
 window.apiPresets={sync:m=>{const matches=Object.keys(presets).filter(k=>presets[k].base===m.baseUrl?.replace(/\/$/,'')&&presets[k].format===m.format);select.value=matches.find(k=>presets[k].model&&presets[k].model===m.model)||matches[0]||'';info();fillModels([]);loadSavedModels();}};
 window.apiPresets.sync({baseUrl:$('member-base').value,format:$('member-format').value,model:$('member-model').value});
})();
