(()=>{const make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};let items=[],icon='',current='';
 const d=make('dialog');d.id='quick-tasks-dialog';d.innerHTML='<div class="dialog-head"><h2>常用任务</h2><button id="quick-close">关闭</button></div><p class="help">保存常用的工作要求。点击任务卡片仅填入聊天框，你可以补充后再发送。</p><div class="quick-toolbar"><select id="quick-list" aria-label="选择常用任务"></select><button id="quick-new">新增任务</button></div><label>任务名称<input id="quick-name" maxlength="60" placeholder="例如：检查项目方案"></label><label>任务内容<textarea id="quick-content" maxlength="8000" placeholder="填写希望 AI 完成的工作、要求和输出格式…"></textarea></label><div class="form-actions"><button id="quick-delete">删除任务</button><button id="quick-save" class="primary">保存任务</button></div><p id="quick-status" role="status"></p>';document.body.append(d);
 function list(){const s=$('quick-list');s.replaceChildren();const blank=make('option','新增任务');blank.value='';s.append(blank);for(const t of items){const o=make('option',t.name);o.value=t.id;s.append(o);}s.value=current;}
 function edit(id){current=id||'';const t=items.find(t=>t.id===id);$('quick-name').value=t?.name||'';$('quick-content').value=t?.content||'';$('quick-delete').disabled=!t;$('quick-status').textContent='';list();}
 async function open(){try{items=await call('quickTasks');edit(items[0]?.id);d.showModal();}catch(e){notify(e.message);}}
 function render(){const welcome=document.querySelector('.welcome');if(!welcome)return;const mark=welcome.querySelector('.welcome-symbol');if(mark){mark.replaceChildren();if(icon){const img=make('img');img.src=icon;img.alt='同桌 AI';mark.append(img);}}const area=welcome.querySelector('.examples');if(!area)return;area.replaceChildren();for(const t of items){const b=make('button');b.className='quick-task';b.append(make('span',t.name),make('span','↗'));b.title=t.content;b.onclick=()=>{if($('prompt').value.trim()&&$('prompt').value!==t.content&&!confirm('用此常用任务替换聊天框中尚未发送的内容？'))return;$('prompt').value=t.content;$('prompt').dispatchEvent(new Event('input',{bubbles:true}));$('prompt').focus();};area.append(b);}if(!items.length)area.append(make('p','还没有常用任务，点击“管理常用任务”添加。'));if(!welcome.querySelector('#quick-manage')){const b=make('button','管理常用任务');b.id='quick-manage';b.className='text-btn';b.onclick=open;area.after(b);}}
 $('quick-list').onchange=()=>edit($('quick-list').value);$('quick-new').onclick=()=>edit('');$('quick-close').onclick=()=>d.close();
 $('quick-save').onclick=async()=>{try{const t=await call('quickTaskSave',{task:{id:current||undefined,name:$('quick-name').value,content:$('quick-content').value}});items=await call('quickTasks');edit(t.id);render();$('quick-status').textContent='任务已保存';}catch(e){$('quick-status').textContent=e.message;}};
 $('quick-delete').onclick=async()=>{try{if(!await call('quickTaskDelete',{id:current}))return;items=await call('quickTasks');edit(items[0]?.id);render();$('quick-status').textContent='任务已删除';}catch(e){$('quick-status').textContent=e.message;}};
 window.quickTaskUI={render};Promise.all([call('quickTasks'),call('appIcon')]).then(([tasks,url])=>{items=tasks;icon=url;render();}).catch(e=>notify(e.message));
})();
