(()=>{
 const make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;},call=(n,a)=>window.roundtable.call(n,a),$=id=>document.getElementById(id);
 const d=make('dialog');d.id='skills-dialog';d.innerHTML='<div class="dialog-head"><h2>技能库设置</h2><button id="skills-close">关闭</button></div><p class="help">技能是提供给 AI 的方法与输出规范，不安装软件、不自动执行脚本，也不自动加载文档中引用的文件。</p><div class="skills-toolbar"><select id="skills-list"><option value="">新建技能</option></select><button id="skills-new">新建</button><button id="skills-import">导入 MD / TXT</button><button id="skills-example">分析技能示例</button></div><label>技能名称<input id="skill-name" maxlength="80"></label><label>技能正文<textarea id="skill-content" rows="7" maxlength="16000"></textarea></label><label class="inline"><input id="skill-enabled" type="checkbox" checked>启用技能</label><label>使用范围<select id="skill-access"><option value="all">所有成员可用（黑名单优先）</option><option value="selected">仅允许勾选的成员</option></select></label><div id="skill-members"></div><p class="help">默认使用：该 AI 在自由讨论和“继承默认技能”的节点中自动带上此技能。节点可单独选择技能或不使用。黑名单始终优先。</p><div class="form-actions"><button id="skill-delete">删除技能</button><button id="skill-save" class="primary">保存技能</button></div><p id="skill-status" role="status"></p>';document.body.append(d);
 let list=[],members=[],current='';const open=make('button','技能库设置');open.id='skills-open';open.className='text-btn';$('preferences-open').before(open);
 function edit(id,raw={}){current=id;const s=list.find(s=>s.id===id)||{enabled:true,access:'all',...raw};$('skill-name').value=s.name||'';$('skill-content').value=s.content||'';$('skill-enabled').checked=s.enabled;$('skill-access').value=s.access||'all';$('skills-list').value=id;$('skill-delete').disabled=!id;$('skill-status').textContent='';const area=$('skill-members');area.replaceChildren();const table=make('table');const head=make('tr');for(const text of ['AI 成员','允许','黑名单','默认使用'])head.append(make('th',text));table.append(head);for(const m of members){const row=make('tr');row.append(make('td',m.name));for(const key of ['allowed','denied','defaults']){const cell=make('td'),box=make('input');box.type='checkbox';box.dataset.member=m.id;box.dataset.permission=key;box.checked=!!s[key]?.includes(m.id);box.setAttribute('aria-label',m.name+' '+key);cell.append(box);row.append(cell);}table.append(row);}area.append(table);$('skill-access').onchange=()=>{for(const box of area.querySelectorAll('[data-permission=allowed]'))box.disabled=$('skill-access').value==='all';};$('skill-access').onchange();}
 async function refresh(id=''){list=await call('skillsList');members=(await call('state')).members;const select=$('skills-list');select.replaceChildren();const blank=make('option','新建技能');blank.value='';select.append(blank);for(const s of list){const o=make('option',s.name+(s.enabled?'':' · 已停用'));o.value=s.id;select.append(o);}edit(id);}
 const action=fn=>async()=>{try{await fn();}catch(e){$('skill-status').textContent=e.message;}};
 open.onclick=action(async()=>{await refresh();d.showModal();});$('skills-close').onclick=()=>d.close();$('skills-list').onchange=()=>edit($('skills-list').value);$('skills-new').onclick=()=>edit('');
 $('skills-import').onclick=action(async()=>{const raw=await call('skillsImport');if(raw)edit('',raw);});$('skills-example').onclick=()=>edit('',{name:'证据分析',content:'先明确任务目标与限制。区分已知事实、假设和缺失资料。比较可行方案，给出依据、风险和下一步。无法核实的内容明确标注，不编造引用或执行结果。'});
 $('skill-save').onclick=action(async()=>{const permissions={};for(const key of ['allowed','denied','defaults'])permissions[key]=[...d.querySelectorAll('input[data-permission="'+key+'"]:checked')].map(e=>e.dataset.member);const s=await call('skillsSave',{skill:{id:current||undefined,name:$('skill-name').value,content:$('skill-content').value,enabled:$('skill-enabled').checked,access:$('skill-access').value,...permissions}});await refresh(s.id);$('skill-status').textContent='已保存 · 版本 '+s.revision;});
 $('skill-delete').onclick=action(async()=>{if(await call('skillsDelete',{id:current}))await refresh();});
 window.skillUI={node:async(area,n,memberId,changed,active)=>{const wrapper=make('section');wrapper.className='node-skills';area.append(wrapper);try{const items=await call('skillsList');if(!wrapper.isConnected)return;wrapper.append(make('h3','节点技能'));const mode=make('select');mode.setAttribute('aria-label','节点技能模式');for(const [value,text]of [['inherit','继承成员默认技能'],['manual','指定技能'],['none','不使用技能']]){const o=make('option',text);o.value=value;mode.append(o);}mode.value=n.skillIds===undefined?'inherit':n.skillIds.length?'manual':'none';mode.disabled=active;wrapper.append(mode);const choices=make('div');wrapper.append(choices);const render=()=>{choices.replaceChildren();if(mode.value!=='manual')return;if(!items.length)choices.append(make('p','请先在技能库创建技能。'));for(const s of items){const allowed=s.enabled&&!s.denied.includes(memberId)&&(s.access==='all'||s.allowed.includes(memberId));const label=make('label'),box=make('input');box.type='checkbox';box.value=s.id;box.checked=!!n.skillIds?.includes(s.id);box.disabled=active||!allowed;box.onchange=()=>{n.skillIds=[...choices.querySelectorAll('input:checked')].map(b=>b.value);changed();};label.append(box,make('span',s.name+(allowed?'':' · 不可用')));choices.append(label);}if(n.skillIds?.some(id=>!items.some(s=>s.id===id)))choices.append(make('p','包含已删除技能，请重新选择。'));};mode.onchange=()=>{n.skillIds=mode.value==='inherit'?undefined:[];render();changed();};render();}catch(e){wrapper.textContent=e.message;}}};
 // Hide experimental entry points without deleting stored Manage AI.
 for(const id of ['web-wizard-open','plugins-open','web-transport']){const e=$(id);if(e){e.hidden=true;if(e.tagName==='SELECT')e.parentElement.hidden=true;}}
 const automatic=$('web-mode').querySelector('[value=automation]');automatic.disabled=true;automatic.textContent='自动网页接入（暂不开放）';const terminal=$('member-kind').querySelector('[value=terminal]');terminal.disabled=true;terminal.textContent='终端程序（暂不开放）';$('member-kind').querySelector('[value=web]').textContent='网页手动接力';
 const note=make('p','当前开放 API、Codex 和网页手动接力。已有自动网页／终端配置保留，但运行前需切换接入方式。');note.className='help';$('member-kind').closest('.form-row').after(note);$('web-mode').parentElement.nextElementSibling.nextElementSibling.hidden=true;
})();
