(()=>{
 const $=id=>document.getElementById(id),api=(n,a)=>window.roundtable.call(n,a),make=(t,s)=>{const e=document.createElement(t);if(s)e.textContent=s;return e;};
 const dialog=make('section');dialog.id='steering-dialog';dialog.className='steering-dock';dialog.innerHTML='<div class="steering-heading"><strong id="steering-target">运行状态与补充</strong><span id="steering-elapsed"></span><button id="steering-close" class="text-btn">收起输入</button></div><p id="steering-progress" role="status"></p><div id="steering-editor"><textarea id="steering-text" rows="2" maxlength="8000" placeholder="补充方向，例如：先核实来源，预算控制在 100 元以内…" aria-label="补充要求"></textarea><div class="steering-bottom"><span class="help">补充在后续步骤生效。重新回答会取消当前 API 请求，可能增加调用费用。</span><button id="steering-restart">停止并重新回答</button><button id="steering-next" class="primary">发送补充 ↑</button></div><p id="steering-status" role="status"></p></div>';
 const composer=document.querySelector('.composer');composer.before(dialog);dialog.hidden=true;let target=null,latest=null,expanded=false,sending=false,polling=false;
 function dock(){if(dialog.parentElement?.tagName==='DIALOG'&&dialog.parentElement.open)return;if(dialog.parentElement!==composer.parentElement||dialog.nextElementSibling!==composer)composer.before(dialog);}
 async function refresh(){if(polling)return;polling=true;try{const next=await api('runtimeStatus');if(latest&&!next)expanded=false;latest=next;skip.hidden=latest?.kind!=='discussion';if(!$('steering-text').value.trim())target=latest;dialog.hidden=!latest&&!expanded;if(!dialog.hidden)dock();$('steering-target').textContent=latest?latest.name+' · 运行状态':'补充要求';$('steering-progress').textContent=latest?.progress||'当前没有运行中的任务，可先填写草稿。';const seconds=latest?.startedAt?Math.max(0,Math.floor((Date.now()-Date.parse(latest.startedAt))/1000)):0;$('steering-elapsed').textContent=latest?`已用时 ${Math.floor(seconds/60)}分${seconds%60}秒`:'';$('steering-next').disabled=sending||!latest;$('steering-restart').hidden=!latest?.canRestart;$('steering-restart').disabled=sending;composer.classList.toggle('steering-active',!!latest&&!dialog.hidden&&dialog.parentElement===composer.parentElement);}catch(e){$('steering-progress').textContent=e.message;}finally{polling=false;}}
 const popup=make('dialog');popup.id='workflow-steering-popup';const close=make('button','关闭');close.onclick=()=>{popup.close();dock();};popup.append(close);document.body.append(popup);popup.addEventListener('close',dock);
 async function open(container){expanded=true;await refresh();if(container){container.append(dialog);dialog.hidden=false;}$('steering-editor').hidden=false;$('steering-close').textContent='收起输入';$('steering-text').focus();}
 for(const [parent,id]of [['stop','chat-steer'],['wf-stop','wf-steer'],['manual-stop','manual-steer'],['wf-reject','gate-steer']]){const b=make('button','补充要求');b.id=id;b.type='button';$(parent).before(b);b.onclick=()=>{if(id==='wf-steer'){popup.showModal();open(popup);}else open(b.closest('dialog'));};}
 $('steering-close').onclick=()=>{$('steering-editor').hidden=!$('steering-editor').hidden;$('steering-close').textContent=$('steering-editor').hidden?'展开输入':'收起输入';if(!latest){expanded=false;dialog.hidden=true;}};
 async function submit(restart){if(sending)return;sending=true;$('steering-next').disabled=true;$('steering-restart').disabled=true;try{if(!target)throw Error('没有正在运行的任务。');const r=await api('steer',{kind:target.kind,id:target.id,text:$('steering-text').value,restart});$('steering-status').textContent=r.message;$('steering-text').value='';expanded=true;}catch(e){$('steering-status').textContent=e.message;}finally{sending=false;await refresh();}}
  $('steering-next').onclick=()=>submit(false);$('steering-restart').onclick=()=>submit(true);
 $('steering-text').oninput=()=>{if(!$('steering-text').value.trim())target=latest;};
 $('steering-text').onkeydown=e=>{if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();submit(false);}};
 const skip=make('button','跳过当前成员');skip.id='skip-member';$('stop').before(skip);skip.onclick=async()=>{try{const s=await api('steeringStatus');if(s?.kind!=='discussion')throw Error('当前没有运行中的讨论室。');await api('skipMember',{id:s.id});}catch(e){alert(e.message);}};
 const log=make('details');log.id='workflow-supplements';const title=make('summary','运行中补充记录'),content=make('div');log.append(title,content);$('wf-run-status').after(log);log.hidden=true;
 function show(run){content.replaceChildren();const entries=run?.supplements||[];log.hidden=!entries.length;for(const s of entries){const p=make('p',s.text);p.style.whiteSpace='pre-wrap';p.style.overflowWrap='anywhere';p.title='适用节点：'+s.targets.join(', ');content.append(p);}}
 window.roundtable.subscribe(e=>{if(e.type==='workflow')show(e.run);if(['workflow','message','running','idle'].includes(e.type))refresh();});
 setInterval(refresh,1000);refresh();
 $('wf-history').addEventListener('change',async()=>{try{const s=await api('workflowState');show(s.runs.find(r=>r.id===$('wf-history').value));}catch{}});
})();
