(()=>{
 const $=id=>document.getElementById(id),call=(n,a)=>window.roundtable.call(n,a),d=document.createElement('dialog');d.id='web-wizard';d.innerHTML='<div class="dialog-head"><h2>连接 AI 网页</h2><button id="ww-close">关闭</button></div><p id="ww-site"></p><label class="inline"><input id="ww-permission" type="checkbox">我已确认该网站允许此自动接入方式</label><p>① 打开窗口，在网站内登录。若内置窗口无法登录，可返回使用浏览器扩展。</p><button id="ww-open">打开登录窗口</button><p>② 登录后先点“自动识别”。无法识别的部分再点选；如果没有已有回复，请先在网页中完成一次普通对话。配置保存后可复用。</p><button id="ww-detect">自动识别网页控件</button><div id="ww-picks"></div><p class="help">回复区域请选择完整的一条 AI 答案，不要选择整个聊天列表。页面结构改变后可能需要重新点选。</p><p>③ 发送一条连接测试消息，确认能发送和读取，再保存成员。</p><button id="ww-test">发送测试消息</button><button id="ww-save">保存成员</button><p id="ww-status" role="status"></p>';document.body.append(d);
 let current;$('ww-permission').onchange=()=>{$('web-permission').checked=$('ww-permission').checked;};
 const member=()=>({...formMember(),webMode:'automation',webTransport:'window',automationAcknowledged:$('web-permission').checked});
 const run=fn=>async()=>{const buttons=[...d.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){$('ww-status').textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}};
 $('web-wizard-open').onclick=()=>{try{const u=new URL($('member-url').value.trim());const blocked=['claude.ai','claude.com'].some(h=>u.hostname===h||u.hostname.endsWith('.'+h));$('ww-site').textContent=blocked?'此网站在本程序中仅提供手动接力，不启用自动连接。':'识别到网站：'+u.hostname+'。当前为引导式适配，尚未验证。';$('ww-permission').checked=$('web-permission').checked;d.showModal();$('ww-open').disabled=blocked;$('ww-test').disabled=blocked;$('ww-status').textContent='自动连接需要勾选成员设置中的“网站提供方明确允许此自动接入方式”。登录、验证码和网站限制由你处理。';}catch{$('form-status').textContent='请先粘贴完整的聊天网页网址。';}};
 $('ww-close').onclick=()=>d.close();$('ww-open').onclick=run(async()=>{current=member();await call('webWindowOpen',{member:current});$('ww-status').textContent='请在新窗口登录，然后返回这里点选控件。';});
 for(const [kind,label]of [['input','点选输入框'],['send','点选发送按钮'],['response','点选 AI 回复区域'],['busy','点选停止按钮（可选）']]){const b=document.createElement('button');b.textContent=label;b.onclick=run(async()=>{current=member();$('ww-status').textContent='请到网页窗口点击对应位置，Esc 取消。';const selector=await call('webWindowPick',{member:current,kind});$('selector-'+kind).value=selector;$('ww-status').textContent=label+'：已记录。';});$('ww-picks').append(b);}
 $('ww-detect').onclick=run(async()=>{const result=await call('webWindowDetect',{member:member()});for(const [kind,value]of Object.entries(result.selectors))$('selector-'+kind).value=value;const names={input:'输入框',send:'发送按钮',response:'AI 回复区域'};$('ww-status').textContent=result.missing.length?'还需点选：'+result.missing.map(k=>names[k]).join('、'):'候选控件已识别，请发送测试消息验证。';});
 $('ww-test').onclick=run(async()=>{$('ww-status').textContent='正在发送测试并等待回复…';const result=await call('webWindowTest',{member:member()});$('ww-status').textContent=result.message;});
 $('ww-save').onclick=run(async()=>{$('web-mode').value='automation';$('web-transport').value='window';await saveMember();$('ww-status').textContent='已保存适配。未经测试的配置请先测试后再加入讨论。';});
})();
