(()=>{
  const $=id=>document.getElementById(id),api=(n,a)=>window.roundtable.call(n,a),make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
  const titles={input:'任务输入',ai:'AI 任务',execute:'执行任务',merge:'并行汇合',approval:'人工确认',output:'最终输出'};
  const roleTitles={a:'AI A / 规划者',b:'AI B / 审查者',executor:'执行者',reviewer:'验收者'};
  const statusTitles={pending:'等待上游',queued:'排队中',running:'运行中',waiting:'等待你确认',complete:'完成',error:'失败',cancelled:'已停止'};
  let graph=null,members=[],graphs=[],runs=[],run=null,nodeId=null,source=null,active=false,dirty=false,zoom=0.85,gateId=null,checking=false;
  const host=make('section',undefined,'workflow');host.id='workflow';
  host.innerHTML=`<div class="wf-top"><div><div class="eyebrow">AI WORKFLOW STUDIO</div><h1>协作，从搭好流程开始。</h1></div><button id="wf-members">管理 AI</button></div>
  <div class="wf-templates"><button data-template="duo"><strong>01　双 AI 协作</strong><small>并行思考 → 交叉审查 → 执行与验收</small></button><button data-template="pipeline"><strong>02　分工流水线</strong><small>规划 → 审查 → 执行 → 验收</small></button><button data-template="blank"><strong>＋　自由搭建</strong><small>从空白画布创建自己的协作流程</small></button></div>
  <div class="wf-toolbar"><input id="wf-name" aria-label="工作流名称" placeholder="工作流名称"><select id="wf-saved" aria-label="我的工作流"><option value="">我的工作流…</option></select><button id="wf-save">保存</button><button id="wf-copy">另存为新工作流</button><button id="wf-import">导入</button><button id="wf-export">导出</button><button id="wf-check">检查配置</button><span id="wf-dirty"></span></div>
  <div class="wf-body"><aside class="wf-palette"><h3>流程积木</h3><div id="wf-blocks"></div><h3>拖入 AI</h3><div id="wf-ai-list"></div><p>拖动积木到画布；拖动 AI 到节点。<br>先点「连接下一步」，再点目标的「接收连接」。删除连接：选中积木，在右侧管理连接。</p><button id="wf-fit">回到起点</button><div class="wf-zoom"><button id="wf-minus">−</button><span id="wf-scale">85%</span><button id="wf-plus">＋</button></div></aside>
  <div id="wf-viewport"><div id="wf-canvas"><svg id="wf-edges"></svg><div id="wf-nodes"></div></div></div>
  <aside class="wf-inspector"><h3>角色填位</h3><div id="wf-roles"></div><hr><h3 id="wf-node-title">选择一个节点</h3><div id="wf-node-form"></div><div id="wf-issues" role="status"></div></aside></div>
  <div class="wf-bottom"><div class="wf-task"><textarea id="wf-task" rows="2" placeholder="输入本次任务与文字资料，所有 AI 节点都会收到任务目标…"></textarea><div class="wf-actions"><button id="wf-directory">选择执行目录</button><span id="wf-path">未选择 · 纯讨论流程不需要目录</span><button id="wf-start" class="primary">运行工作流 →</button><button id="wf-stop" class="danger" hidden>停止</button></div></div><div class="wf-history"><select id="wf-history" aria-label="运行历史"><option value="">运行记录…</option></select><button id="wf-result">导出结果</button><p id="wf-run-status">先选工作流，再为任务节点选择 AI；可在多个步骤使用同一个模型。</p></div></div><div id="wf-notice" class="notice" hidden></div>`;
  document.body.append(host);
  const catalog=host.querySelector('.wf-templates');catalog.classList.add('workflow-catalog');catalog.replaceChildren();
  function catalogCards(){catalog.replaceChildren();graphs.forEach((g,index)=>{const card=make('div',undefined,'workflow-card'),open=make('button');open.className='workflow-card-open';open.append(make('strong',String(index+1).padStart(2,'0')+'　'+g.name),make('small',g.nodes.length+' 个积木 · '+(g.id.startsWith('builtin_')?'内置工作流':'已保存')));open.querySelector('small').dataset.uiText='true';if(g.id.startsWith('builtin_')&&['双 AI 协作','分工流水线'].includes(g.name)){const title=open.querySelector('strong');title.textContent=g.name;title.dataset.uiText='true';}open.disabled=active;open.onclick=()=>{if(dirty&&!confirm('放弃当前未保存的修改，切换工作流？'))return;load(g);};const del=make('button','删除');del.className='workflow-card-delete';del.setAttribute('aria-label','删除工作流：'+g.name);del.disabled=active;del.onclick=guard(async()=>{if(await api('workflowDelete',{id:g.id})){if(graph?.id===g.id)load(await api('workflowTemplate',{kind:'blank'}));await sync();}});card.append(open,del);catalog.append(card);});const add=make('button','＋ 新建工作流');add.className='workflow-new';add.disabled=active;add.onclick=guard(async()=>{if(dirty&&!confirm('放弃当前未保存的修改？'))return;load(await api('workflowTemplate',{kind:'blank'}));});catalog.append(add);}
  const deleteAll=make('button','删除全部工作流');deleteAll.id='wf-delete-all';deleteAll.className='text-btn';$('wf-export').after(deleteAll);deleteAll.onclick=async()=>{try{if(await api('workflowDeleteAll')){load(await api('workflowTemplate',{kind:'blank'}));await sync();}}catch(e){note(e.message);}};
  host.querySelector('.wf-top h1').textContent='设计你的协作流程';
  const trial=make('details');trial.id='wf-trial';trial.append(make('summary','工作流试运行与附件（可选）'));const bottom=host.querySelector('.wf-bottom');bottom.before(trial);trial.append(bottom);
  const usage=make('p','保存工作流后，返回讨论室，在“本对话的协作方式”中选择使用。','help');host.querySelector('.wf-toolbar').after(usage);
  const roleBox=make('details');roleBox.id='wf-role-settings';roleBox.append(make('summary','共用角色设置 · 全流程共用'));const roles=$('wf-roles'),roleHeading=roles.previousElementSibling;roleHeading.remove();roles.before(roleBox);roleBox.append(make('p','每个积木只使用一位 AI。这里设置工作流的共用角色，多个积木可以沿用同一个角色。','help'),roles);
  const nav=make('button','工作流','new-room');nav.id='workflow-nav';document.querySelector('.sidebar').insertBefore(nav,$('new-room'));
  const chatNav=make('button','讨论室','text-btn');chatNav.id='discussion-nav';nav.after(chatNav);
  function show(on){document.getElementById('home-view')?.setAttribute('hidden','');document.querySelector('main').hidden=on;host.hidden=!on;nav.classList.toggle('active',on);if(on)requestAnimationFrame(()=>{draw();inspect();});}
  nav.onclick=()=>show(true);chatNav.onclick=()=>show(false);$('new-room').addEventListener('click',()=>show(false));
  const gate=make('dialog');gate.id='wf-gate';gate.innerHTML='<h2 id="wf-gate-title"></h2><p>请核对下面的方案或执行范围。拒绝会停止本次工作流。</p><pre id="wf-gate-content"></pre><div class="form-actions"><button id="wf-reject">拒绝并停止</button><button id="wf-approve" class="primary">确认继续</button></div>';document.body.append(gate);gate.oncancel=e=>e.preventDefault();
  function note(t){$('wf-notice').textContent=t;$('wf-notice').hidden=!t;}
  const guard=fn=>async(...a)=>{try{await fn(...a);}catch(e){note(e.message);}};
  function changed(){dirty=true;run=null;$('wf-dirty').textContent='未保存';draw();}
  function model(n){return n.model||(n.binding?.startsWith('@')?graph.roleModels?.[n.binding.slice(1)]:'')||members.find(m=>m.id===resolve(n))?.model||'';}
  function resolve(n){return n.binding?.startsWith('@')?graph.roles[n.binding.slice(1)]:n.binding;}
  function options(select,value,roleOptions=false,execution=false){select.replaceChildren(make('option','＋ 选择 AI'));select.firstChild.value='';if(roleOptions)for(const [k,label]of Object.entries(roleTitles)){const o=make('option','沿用 '+label);o.value='@'+k;select.append(o);}for(const m of members.filter(m=>!execution||m.kind==='codex'||(m.kind==='terminal'&&m.executionCapable===true))){const o=make('option',m.name+(m.kind==='web'?' · 手动接力':''));o.value=m.id;select.append(o);}select.value=value||'';}
  function renderRoles(){const area=$('wf-roles');area.replaceChildren();for(const [key,title]of Object.entries(roleTitles)){const l=make('label',title),s=make('select');s.dataset.role=key;options(s,graph.roles[key],false,key==='executor'&&graph.nodes.some(n=>n.type==='execute'));s.disabled=active;s.onchange=()=>{graph.roles[key]=s.value;if(graph.roleModels)delete graph.roleModels[key];if(key==='executor'&&!graph.roles.reviewer){graph.roles.reviewer=[graph.roles.a,graph.roles.b].find(x=>x&&x!==s.value)||'';}changed();renderRoles();inspect();};l.append(s);area.append(l);window.modelTree?.attach(s,{getModel:()=>graph.roleModels?.[key],execution:key==='executor'&&graph.nodes.some(n=>n.type==='execute'),pick:choice=>{graph.roles[key]=choice.memberId;graph.roleModels={...graph.roleModels,[key]:choice.model};changed();renderRoles();inspect();}});}}
  function palette(){const area=$('wf-blocks');area.replaceChildren();for(const [type,title]of Object.entries(titles)){const b=make('button','＋ '+title);b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('application/roundtable',JSON.stringify({type}));b.onclick=()=>add(type,Math.round($('wf-viewport').scrollLeft/zoom+90),Math.round($('wf-viewport').scrollTop/zoom+90));area.append(b);}const ai=$('wf-ai-list');ai.replaceChildren();window.modelTree?.palette(ai);}
  document.addEventListener('model-catalog-updated',async()=>{try{members=(await api('membersState')).members;if(graph){palette();draw();renderRoles();}}catch(e){note(e.message);}});
  function add(type,x,y){if(active)return;const n={id:crypto.randomUUID(),type,title:titles[type],binding:'',instruction:'',x:Math.max(0,x),y:Math.max(0,y)};graph.nodes.push(n);nodeId=n.id;changed();inspect();}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&source){source=null;draw();note('已取消连接。');}});
  const guide=make('p','连线：先点「连接下一步」，再点「接收连接」。删除：选中积木 → 右侧「管理连接」。Esc 取消连线。','wf-connect-guide');host.querySelector('.wf-body').before(guide);
  function connect(target){if(active)return;if(!source){note('第一步：点击上游积木的「连接下一步」，再点这里。');return;}if(source===target){source=null;note('不能连接节点自身。');return;}if(!graph.edges.some(e=>e[0]===source&&e[1]===target))graph.edges.push([source,target]);source=null;changed();inspect();note('连线已添加。运行前会检查循环和缺失配置。');}
  function draw(){if(!graph)return;const nodes=$('wf-nodes');nodes.replaceChildren();const width=Math.max(1200,...graph.nodes.map(n=>n.x+320)),height=Math.max(750,...graph.nodes.map(n=>n.y+220));const canvas=$('wf-canvas');canvas.style.width=width+'px';canvas.style.height=height+'px';canvas.style.zoom=zoom;$('wf-scale').textContent=Math.round(zoom*100)+'%';
    for(const n of graph.nodes){const member=members.find(m=>m.id===resolve(n)),s=run?.nodes[n.id],needs=['ai','execute'].includes(n.type);const card=make('div',undefined,'wf-node '+(nodeId===n.id?'selected ':'')+(needs&&!member?'unbound ':'')+(s?.status||''));card.dataset.node=n.id;card.style.left=n.x+'px';card.style.top=n.y+'px';const head=make('div',titles[n.type],'wf-node-type');head.append(make('span',s?statusTitles[s.status]:'','wf-status'));const nodeTitle=make('strong',n.title);if(['任务与资料','独立方案 A','独立方案 B','A 审查 B','B 审查 A','整理最终方案','确认方案','执行任务','独立验收','最终输出',...Object.values(titles)].includes(n.title))nodeTitle.dataset.uiText='true';card.append(head,nodeTitle);const binding=make('button',needs?(member?member.name+(model(n)?' / '+model(n):''):'＋ 选择 AI'):(n.type==='approval'?'由你确认，无需 AI':n.type==='merge'?'等待所有上游完成':'无需 AI'),'wf-binding');binding.onclick=()=>{nodeId=n.id;draw();inspect();$('wf-node-binding')?.focus();};if(!member)binding.dataset.uiText='true';card.append(binding);if(needs&&n.instruction){const duty=n.duty||(['分析','规划','检查','验收','汇总','执行'].find(d=>n.instruction.startsWith({分析:'分析问题',规划:'提出总体框架',检查:'审查上游',验收:'对照原目标',汇总:'整合上游',执行:'落实已确认'}[d]))||'自定义');const badge=make('span',duty,'wf-duty');badge.title=n.instruction;card.append(badge);}const ports=make('div',undefined,'wf-ports'),input=make('button','接收连接'),output=make('button','连接下一步');input.onclick=()=>connect(n.id);output.onclick=()=>{source=n.id;draw();note('下一步：点击目标积木的「接收连接」。按 Esc 取消。');};input.classList.toggle('connection-target',!!source&&source!==n.id&&n.type!=='input');output.classList.toggle('connection-source',source===n.id);input.disabled=active||n.type==='input'||source===n.id;output.disabled=active||n.type==='output';ports.append(input,output);card.append(ports);card.onclick=e=>{if(e.target.closest('button'))return;nodeId=n.id;draw();inspect();};head.onpointerdown=e=>{if(active)return;e.preventDefault();head.setPointerCapture(e.pointerId);const start={x:e.clientX,y:e.clientY,nx:n.x,ny:n.y};head.onpointermove=ev=>{n.x=Math.max(0,start.nx+(ev.clientX-start.x)/zoom);n.y=Math.max(0,start.ny+(ev.clientY-start.y)/zoom);card.style.left=n.x+'px';card.style.top=n.y+'px';edges();};head.onpointerup=()=>{head.onpointermove=null;head.onpointerup=null;nodeId=n.id;changed();inspect();};};card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();e.stopPropagation();if(active||!needs)return;try{const data=JSON.parse(e.dataTransfer.getData('application/roundtable'));if(data.memberId){n.binding=data.memberId;if(data.model)n.model=data.model;else delete n.model;nodeId=n.id;changed();inspect();}}catch{}};nodes.append(card);}edges();}
  function highlightConnection(edge){for(const card of $('wf-nodes').children)card.classList.toggle('connection-preview',!!edge&&edge.includes(card.dataset.node));for(const line of $('wf-edges').children)line.classList.toggle('connection-preview',!!edge&&line.dataset.from===edge[0]&&line.dataset.to===edge[1]);}
  function edges(){const svg=$('wf-edges');svg.replaceChildren();svg.setAttribute('width',parseFloat($('wf-canvas').style.width)||1200);svg.setAttribute('height',parseFloat($('wf-canvas').style.height)||750);for(const [a,b]of graph.edges){const from=graph.nodes.find(n=>n.id===a),to=graph.nodes.find(n=>n.id===b);if(!from||!to)continue;const p=document.createElementNS('http://www.w3.org/2000/svg','path');const portY=(n,last)=>{const el=$('wf-nodes').querySelector('[data-node="'+CSS.escape(n.id)+'"] .wf-ports button:'+(last?'last':'first')+'-child');if(!el)return n.y+176;const box=el.getBoundingClientRect(),base=$('wf-canvas').getBoundingClientRect();if(!box.height||!base.width)return n.y+176;return (box.top+box.height/2-base.top)/zoom;};const x=from.x+230,y=portY(from,true),tx=to.x,ty=portY(to,false);p.setAttribute('d',`M ${x} ${y} C ${x+70} ${y}, ${tx-70} ${ty}, ${tx} ${ty}`);p.setAttribute('class','wf-edge');p.dataset.from=a;p.dataset.to=b;svg.append(p);}}
  function inspect(){highlightConnection(null);const area=$('wf-node-form');area.replaceChildren();const n=graph.nodes.find(n=>n.id===nodeId);$('wf-node-title').textContent=n?n.title:'选择一个节点';if(!n)return;
    const field=(label,id,value,tag='input')=>{const l=make('label',label),input=make(tag);input.id=id;input.value=value||'';input.disabled=active;l.append(input);area.append(l);return input;};
    field('节点名称','wf-node-name',n.title).onchange=e=>{n.title=e.target.value.slice(0,80)||titles[n.type];changed();};
    if(['ai','execute'].includes(n.type)){window.skillUI?.node(area,n,resolve(n),()=>{changed();},active);const select=field('由谁负责 · 只选一位 AI','wf-node-binding','','select');options(select,n.binding,true,n.type==='execute');select.onchange=()=>{n.binding=select.value;delete n.model;changed();inspect();};window.modelTree?.attach(select,{getModel:()=>model(n),execution:n.type==='execute',pick:choice=>{n.binding=choice.memberId;if(choice.model)n.model=choice.model;else delete n.model;changed();inspect();}});const presets=n.type==='execute'?{执行:'落实已确认的方案，只在指定目录内工作。报告实际修改、执行结果和验证证据；不要声称完成未执行的操作。'}:{分析:'分析问题、已有证据与关键假设，给出独立判断，明确不确定性。',规划:'提出总体框架与可操作步骤，说明依赖、优先级和完成标准。',检查:'审查上游方案的逻辑、事实与遗漏，逐项指出问题及修改建议。',验收:'对照原目标和完成标准检查结果，说明通过项、未完成项与可核查证据。',汇总:'整合上游意见，区分共识、分歧和证据缺口，提出下一步建议。'};const prompt=field('职责与输出要求','wf-node-instruction',n.instruction,'textarea');prompt.rows=4;window.dutyOptions?.(area,n,prompt,presets,changed,active);if(n.type==='ai')area.append(make('p','需要操作电脑或文件时，请使用“执行任务”积木，并选择本地执行者。','help'));}
    const upstream=make('div',undefined,'wf-upstream');upstream.id='wf-connections';upstream.append(make('h3','管理连接'));const links=graph.edges.filter(e=>e.includes(n.id));if(!links.length)upstream.append(make('p','这个积木还没有连接。'));for(const edge of links){const label=graph.nodes.find(x=>x.id===edge[0])?.title+' → '+graph.nodes.find(x=>x.id===edge[1])?.title;const row=make('div',undefined,'wf-connection-row');row.append(make('span',label));const remove=make('button','删除连接');remove.disabled=active;row.onmouseenter=()=>highlightConnection(edge);row.onmouseleave=()=>highlightConnection(null);remove.onfocus=()=>highlightConnection(edge);remove.onblur=()=>highlightConnection(null);remove.onclick=()=>{const en=document.documentElement.lang==='en';if(!confirm((en?'Delete this connection?\n':'删除这条连接？\n')+label))return;graph.edges=graph.edges.filter(e=>e!==edge);changed();inspect();};row.append(remove);upstream.append(row);}area.prepend(upstream);
    const actions=make('div',undefined,'wf-node-actions');const del=make('button','删除积木');del.disabled=active;del.onclick=()=>{graph.nodes=graph.nodes.filter(x=>x.id!==n.id);graph.edges=graph.edges.filter(e=>!e.includes(n.id));nodeId=null;changed();inspect();};actions.append(del);area.append(actions);
    if(run?.nodes[n.id]){const s=run.nodes[n.id],pre=make('pre',s.text||s.error||statusTitles[s.status],'wf-output');if(s.skills?.length)area.append(make('p','Skills: '+s.skills.map(x=>x.name+' v'+x.revision).join(' · '),'skill-usage'));pre.id='wf-node-output';area.append(make('h3','本次节点结果'),pre);if(s.error)area.append(make('p',s.error,'wf-error'));if(!active){const retry=make('button','从此节点重跑');retry.onclick=guard(()=>start(n.id));area.append(retry);}}
  }
  async function validate(){const issues=await api('workflowValidate',{graph});const area=$('wf-issues');area.replaceChildren();if(!issues.length)area.append(make('p','✓ 流程配置完整'));for(const i of issues){const b=make('button',i.message);b.onclick=()=>{if(i.nodeId){nodeId=i.nodeId;draw();inspect();const n=graph.nodes.find(n=>n.id===nodeId);$('wf-viewport').scrollTo({left:Math.max(0,n.x*zoom-30),top:Math.max(0,n.y*zoom-40),behavior:'smooth'});}};area.append(b);}return issues;}
  function load(g){$('wf-canvas').style.marginLeft='0px';$('wf-canvas').style.marginTop='0px';graph=structuredClone(g);nodeId=null;run=null;dirty=false;source=null;$('wf-name').value=graph.name;$('wf-dirty').textContent='';$('wf-issues').replaceChildren();renderRoles();draw();inspect();$('wf-viewport').scrollTo(0,0);}
  function saved(){catalogCards();const s=$('wf-saved');s.replaceChildren(make('option','选择工作流…'));s.firstChild.value='';s.firstChild.dataset.uiText='';for(const g of graphs){const o=make('option',g.name);o.value=g.id;s.append(o);}s.value=graph?.id||'';const h=$('wf-history');h.replaceChildren(make('option','运行记录…'));h.firstChild.value='';for(const r of runs){const o=make('option',new Date(r.createdAt).toLocaleString()+' · '+r.graph.name+' · '+(statusTitles[r.status]||r.status));o.value=r.id;h.append(o);}}
  async function sync(){const [s,w]=await Promise.all([api('membersState'),api('workflowState')]);members=s.members;graphs=w.graphs;runs=w.runs;active=!!w.active||!!s.active;saved();palette();if(!graph)load(graphs[0]||await api('workflowTemplate',{kind:'duo'}));busy();handleGate(w.gate);}
  function busy(){for(const id of ['wf-save','wf-copy','wf-import','wf-saved','wf-name','wf-task','wf-directory'])if($(id).disabled!==active)$(id).disabled=active;$('wf-start').disabled=active;$('wf-stop').hidden=!active;host.querySelectorAll('[data-template]').forEach(b=>b.disabled=active);}
  function handleGate(job){if(job&&job.id!==gateId){gateId=job.id;$('wf-gate-title').textContent=job.name;$('wf-gate-content').textContent=job.prompt;if(!gate.open)gate.showModal();}else if(!job&&gateId){gateId=null;gate.close();}}
  async function start(from){if((await validate()).length){note('请先补齐右侧的配置问题。');return;}const workspace=$('wf-path').dataset.path||'';await api('workflowStart',{graph,task:$('wf-task').value,workspace,from,previousId:from?run?.id:undefined});active=true;dirty=false;$('wf-dirty').textContent='已保存';busy();renderRoles();note('流程已启动。网页节点需要手动交回回复；执行节点将请求确认。');}
  $('wf-start').onclick=guard(()=>start());$('wf-stop').onclick=guard(()=>api('stop'));$('wf-check').onclick=guard(validate);$('wf-members').onclick=()=>{$('settings').click();};
  const nameInput=$('wf-name');let naming=false;nameInput.addEventListener('compositionstart',()=>{naming=true;});const keepName=()=>{if(!graph)return;graph.name=nameInput.value;dirty=true;run=null;$('wf-dirty').textContent='未保存';};nameInput.addEventListener('compositionend',()=>{naming=false;keepName();});nameInput.addEventListener('input',()=>{if(!naming)keepName();});nameInput.addEventListener('change',keepName);
  $('wf-save').onclick=guard(async()=>{graph=await api('workflowSave',{graph});dirty=false;$('wf-dirty').textContent='已保存';await sync();});
  $('wf-copy').onclick=guard(async()=>{graph.id=crypto.randomUUID();graph.name+=' · 副本';graph=await api('workflowSave',{graph});load(graph);await sync();});
  $('wf-export').onclick=guard(()=>api('workflowExport',{graph}));$('wf-import').onclick=guard(async()=>{if(dirty&&!confirm('放弃当前未保存的画布修改？'))return;const g=await api('workflowImport');if(g){load(g);await sync();}});
  $('wf-directory').onclick=guard(async()=>{const p=await api('workflowDirectory');if(p){$('wf-path').textContent=p;$('wf-path').dataset.path=p;}});
  $('wf-result').onclick=guard(()=>{if(!run)throw Error('请先选择运行记录。');return api('workflowExportRun',{id:run.id});});
  $('wf-saved').onchange=guard(()=>{if(!$('wf-saved').value)return;if(dirty&&!confirm('放弃当前未保存的画布修改？'))return;load(graphs.find(g=>g.id===$('wf-saved').value));});
  $('wf-history').onchange=guard(()=>{if(active)return;if(dirty&&!confirm('放弃当前未保存的画布修改？'))return;const r=runs.find(r=>r.id===$('wf-history').value);if(r){load(r.graph);run=r;$('wf-task').value=r.task;$('wf-path').textContent=r.workspace||'未选择';$('wf-path').dataset.path=r.workspace||'';draw();inspect();$('wf-run-status').textContent=statusTitles[r.status]||r.status;}});
  host.querySelectorAll('[data-template]').forEach(b=>b.onclick=guard(async()=>{if(dirty&&!confirm('放弃当前未保存的画布修改？'))return;load(await api('workflowTemplate',{kind:b.dataset.template}));}));
  $('wf-viewport').ondragover=e=>e.preventDefault();$('wf-viewport').ondrop=e=>{e.preventDefault();if(active)return;try{const data=JSON.parse(e.dataTransfer.getData('application/roundtable')),rect=$('wf-canvas').getBoundingClientRect();if(data.type)add(data.type,(e.clientX-rect.left)/zoom,(e.clientY-rect.top)/zoom);}catch{}};
  $('wf-minus').onclick=()=>{zoom=Math.max(.03,zoom-.1);draw();};$('wf-plus').onclick=()=>{zoom=Math.min(1.4,zoom+.1);draw();};$('wf-fit').onclick=()=>{$('wf-canvas').style.marginLeft='0px';$('wf-canvas').style.marginTop='0px';draw();$('wf-viewport').scrollTo(0,0);};
  $('wf-approve').onclick=guard(()=>api('workflowGate',{id:gateId,approve:true}));$('wf-reject').onclick=guard(()=>api('workflowGate',{id:gateId,approve:false}));
  window.roundtable.subscribe(e=>{if(e.type==='workflow'){active=e.run.status==='running';if(e.run.graph.id===graph?.id){run=e.run;if(!host.hidden){draw();inspect();}$('wf-run-status').textContent=(statusTitles[e.run.status]||e.run.status)+' · '+Object.values(e.run.nodes).filter(s=>s.status==='complete').length+'/'+e.run.graph.nodes.length+' 个节点';}busy();if(!active){sync().catch(err=>note(err.message));renderRoles();}}if(e.type==='workflowFailure')note(e.error);});
  setInterval(async()=>{if(checking)return;checking=true;try{const w=await api('workflowPoll');handleGate(w.gate);if(w.active){active=true;busy();}if(!host.hidden&&!active){const s=await api('membersState');if(JSON.stringify(members)!==JSON.stringify(s.members)){members=s.members;palette();renderRoles();draw();}}}catch{}finally{checking=false;}},1000);
  const overview=make('button','适应全部节点');overview.id='wf-overview';overview.onclick=()=>{
    if(!graph?.nodes.length)return;const viewport=$('wf-viewport'),canvas=$('wf-canvas');canvas.style.marginLeft='0px';canvas.style.marginTop='0px';
    const minX=Math.min(...graph.nodes.map(n=>n.x)),minY=Math.min(...graph.nodes.map(n=>n.y)),maxX=Math.max(...graph.nodes.map(n=>n.x+230)),maxY=Math.max(...graph.nodes.map(n=>n.y+210));
    const width=maxX-minX,height=maxY-minY;let vw=viewport.clientWidth,vh=viewport.clientHeight;
    zoom=Math.min(1,(vw-48)/Math.max(1,width),(vh-48)/Math.max(1,height));draw();
    vw=viewport.clientWidth;vh=viewport.clientHeight;
    const dx=(vw-width*zoom)/2-minX*zoom,dy=(vh-height*zoom)/2-minY*zoom;
    canvas.style.marginLeft=Math.max(0,dx)/zoom+'px';canvas.style.marginTop=Math.max(0,dy)/zoom+'px';
    canvas.style.width=Math.max(parseFloat(canvas.style.width),(vw+Math.max(0,-dx))/zoom)+'px';canvas.style.height=Math.max(parseFloat(canvas.style.height),(vh+Math.max(0,-dy))/zoom)+'px';
    viewport.scrollTo(Math.max(0,-dx),Math.max(0,-dy));
  };$('wf-fit').after(overview);
  const attachButton=make('button','＋ 附件 / 资料');attachButton.id='wf-attachments';attachButton.onclick=guard(async()=>{if(active)throw Error('请先停止运行再修改附件。');await window.attachmentUI.open('workflow:'+graph.id,files=>{attachButton.textContent=files.length?`附件 / 资料（${files.length}）`:'＋ 附件 / 资料';});});$('wf-directory').before(attachButton);
  setInterval(async()=>{if(!host.hidden&&graph){try{const files=await api('attachmentsList',{scope:'workflow:'+graph.id});attachButton.textContent=files.length?`附件 / 资料（${files.length}）`:'＋ 附件 / 资料';attachButton.disabled=active;}catch{}}},2000);
  document.querySelector('.sidebar-footer small').textContent='AI Roundtable · 0.11.7';
  const help=make('details');help.className='workflow-help';help.append(make('summary','工作流使用帮助'));const guideText=host.querySelector('.wf-connect-guide'),usageText=host.querySelector('p.help');host.querySelector('.wf-toolbar').after(help);if(usageText)help.append(usageText);if(guideText)help.append(guideText);
  show(true);sync().catch(e=>note(e.message));
})();


