const fs=require('node:fs'),path=require('node:path');
const {randomUUID}=require('node:crypto');
const {template,cleanGraph,validateGraph,resolveMember,needsAI,WorkflowRunner}=require('./workflow.cjs');
const {ManualAdapter}=require('./adapters/manual.cjs');
const {exportDocument}=require('./export.cjs');
function createWorkflows({store,getMembers,getAttachments=()=>[],getSkillStamp=()=>'',prepare=p=>p,send,assertIdle,preflight,dialog,window,emit,onRun=()=>{}}){
  let graphs=store.read('workflows',[]),runs=store.read('workflow-runs',[]);
  if(!store.read('workflow-catalog-meta',{}).initialized){const builtins=['duo','pipeline'].map(kind=>({...template(kind),id:'builtin_'+kind}));graphs=[...builtins.filter(g=>!graphs.some(x=>x.id===g.id)),...graphs];store.write('workflows',graphs);store.write('workflow-catalog-meta',{initialized:true});}
  const overwrite=(name,data)=>{store.write(name,data);fs.copyFileSync(path.join(store.root,name+'.json'),path.join(store.root,name+'.json.bak'));};
  const confirmDelete=async(message,detail)=>{const r=await dialog.showMessageBox(window(),{type:'warning',title:'确认删除',message,detail,buttons:['取消','确认删除'],defaultId:0,cancelId:0,noLink:true});assertIdle();return r.response===1;};
  for(const r of runs)if(r.status==='running'){r.status='cancelled';for(const n of Object.values(r.nodes))if(['running','waiting','queued','pending'].includes(n.status)){n.status='cancelled';n.error='程序上次退出，未自动重发。';}}
  const gate=new ManualAdapter();
  const runner=new WorkflowRunner({send,prepare,confirm:async({title,prompt,signal})=>{await gate.send({member:{id:'approval',name:title},prompt,signal});},persist:r=>{const i=runs.findIndex(x=>x.id===r.id);if(i<0)runs.unshift(r);else runs[i]=r;runs=runs.slice(0,30);store.write('workflow-runs',runs);onRun(r,true);},emit:e=>{if(e.type==='workflow')onRun(e.run,false);emit(e);}});
  const save=g=>{const graph=cleanGraph(g);const i=graphs.findIndex(x=>x.id===graph.id);if(i<0)graphs.push(graph);else graphs[i]=graph;store.write('workflows',graphs);return graph;};
  const handlers={
    workflowState:()=>({graphs,runs,active:runner.active?.run.id||null,gate:gate.status()}),
    workflowTemplate:({kind})=>{assertIdle();return template(kind);},
    workflowSave:({graph})=>{assertIdle();const existing=graphs.find(g=>g.id===graph.id);if(existing?.id.startsWith('builtin_')&&existing.name!==graph.name)graph={...graph,id:randomUUID()};return save(graph);},
    workflowDelete:async({id})=>{assertIdle();const g=graphs.find(g=>g.id===id);if(!g)throw Error('工作流不存在。');if(!await confirmDelete(`删除工作流“${g.name}”？`,'删除后无法撤销。已有聊天记录和运行结果会保留。'))return false;graphs=graphs.filter(g=>g.id!==id);overwrite('workflows',graphs);emit({type:'workflowCatalog'});return true;},
    workflowDeleteAll:async()=>{assertIdle();if(!graphs.length)return false;if(!await confirmDelete(`删除全部 ${graphs.length} 个工作流？`,'包括内置和自建工作流。删除后不会自动恢复；已有聊天记录和运行结果会保留。'))return false;graphs=[];overwrite('workflows',graphs);emit({type:'workflowCatalog'});return true;},
    workflowValidate:({graph})=>validateGraph(graph,getMembers()).issues,
    workflowDirectory:async()=>{assertIdle();const r=await dialog.showOpenDialog(window(),{title:'选择工作流执行目录',properties:['openDirectory','createDirectory']});return r.canceled?'':r.filePaths[0];},
    workflowGate:({id,approve})=>{if(!gate.pending||gate.pending.id!==id)throw Error('确认请求已失效。');if(approve!==true){runner.stop();return true;}gate.submit(id,'用户已确认');return true;},
    workflowStart:({graph,task,workspace,from,previousId})=>{
      assertIdle();const {graph:g,issues}=validateGraph(graph,getMembers());if(issues.length)throw Error(issues.map(x=>x.message).join('\n'));
      if(typeof task!=='string'||!task.trim()||task.length>20000)throw Error('请填写任务（最多 20,000 字符）。');
      if(g.nodes.some(n=>n.type==='execute')&&(!path.isAbsolute(workspace||'')||!fs.existsSync(workspace)||!fs.statSync(workspace).isDirectory()))throw Error('请先选择有效的执行工作目录。');
      const members=getMembers().filter(m=>g.nodes.some(n=>needsAI(n)&&resolveMember(g,n)===m.id));members.forEach(preflight);
      const previous=previousId?runs.find(r=>r.id===previousId):null;
      save(g);runner.run(g,members,{skillStamp:getSkillStamp(),task,workspace,previous,from,attachments:getAttachments(g.id)}).catch(e=>emit({type:'workflowFailure',error:e.message}));return true;
    },
    workflowExport:async({graph})=>{const g=cleanGraph(graph);g.id=randomUUID();for(const k of Object.keys(g.roles))g.roles[k]='';for(const n of g.nodes)if(n.binding&&!n.binding.startsWith('@'))n.binding='';const r=await dialog.showSaveDialog(window(),{defaultPath:'工作流模板.json',filters:[{name:'工作流模板',extensions:['json']}]});if(!r.canceled)fs.writeFileSync(r.filePath,JSON.stringify(g,null,2),'utf8');return !r.canceled;},
    workflowImport:async()=>{assertIdle();const r=await dialog.showOpenDialog(window(),{filters:[{name:'工作流模板',extensions:['json']}],properties:['openFile']});if(r.canceled)return null;if(fs.statSync(r.filePaths[0]).size>1000000)throw Error('模板过大。');const g=cleanGraph(JSON.parse(fs.readFileSync(r.filePaths[0],'utf8')));g.id=randomUUID();for(const k of Object.keys(g.roles))g.roles[k]='';for(const n of g.nodes)if(n.binding&&!n.binding.startsWith('@'))n.binding='';return save(g);},
    workflowExportRun:async({id})=>{const r=runs.find(x=>x.id===id);if(!r)throw Error('运行记录不存在。');const markdown=`# ${r.graph.name}\n\n${r.task}\n\n`+(r.supplements||[]).map(s=>`### 用户运行中补充 · ${s.at}\n\n${s.text}\n\n适用节点：${s.targets.join(', ')}\n\n`).join('')+r.graph.nodes.map(n=>`## ${n.title} · ${r.nodes[n.id].status}\n\n${r.nodes[n.id].text}\n${r.nodes[n.id].error||''}`).join('\n\n');return exportDocument({title:r.graph.name+'结果',markdown,dialog,window:window()});}
  };
  function startInRoom({graphId,task,workspace,roomId,materials,attachments=[],includeGraphAttachments=true,beforeStart=()=>{}}){assertIdle();const raw=graphs.find(g=>g.id===graphId);if(!raw)throw Error('工作流模板不存在，请重新选择或先到画布保存模板。');const {graph,issues}=validateGraph(raw,getMembers());if(issues.length)throw Error(issues.map(x=>x.message).join('\n'));if(typeof task!=='string'||!task.trim()||task.length>20000)throw Error('请填写任务，最多20,000字。');if(graph.nodes.some(n=>n.type==='execute')&&(!path.isAbsolute(workspace||'')||!fs.existsSync(workspace)||!fs.statSync(workspace).isDirectory()))throw Error('此工作流包含执行节点，请先选择有效的执行目录。');const members=getMembers().filter(m=>graph.nodes.some(n=>needsAI(n)&&resolveMember(graph,n)===m.id));members.forEach(preflight);const all=[...(includeGraphAttachments?getAttachments(graph.id):[]),...attachments];const unique=[...new Map(all.map(a=>[a.attachmentId||a.id,a])).values()];beforeStart();runner.run(graph,members,{skillStamp:getSkillStamp(),task,workspace,roomId,materials,attachments:unique}).catch(e=>emit({type:'workflowFailure',error:e.message}));return true;}
  const purgeRoomRuns=ids=>{runs=runs.filter(r=>!ids.includes(r.roomId));overwrite('workflow-runs',runs);};
  async function retryInRoom({roomId,runId,nodeId}){assertIdle();const requested=runs.find(r=>r.id===runId&&r.roomId===roomId);const root=requested?.rootRunId||requested?.id;const previous=requested&&runs.find(r=>r.roomId===roomId&&(r.id===root||r.rootRunId===root));if(!previous)throw Error('原运行记录已不存在，无法从此处重试。');if(!['error','cancelled'].includes(previous.nodes[nodeId]?.status))throw Error('该积木在最新一次续跑中已完成或无需重试，请查看最新结果。');const {graph,issues}=validateGraph(previous.graph,getMembers());if(issues.length)throw Error(issues.map(x=>x.message).join('\n'));require('./resume-selection.cjs').selectedResume(graph,previous,nodeId);const members=getMembers().filter(m=>graph.nodes.some(n=>needsAI(n)&&resolveMember(graph,n)===m.id));members.forEach(preflight);if(graph.nodes.some(n=>n.type==='execute')&&(!path.isAbsolute(previous.workspace||'')||!fs.existsSync(previous.workspace)||!fs.statSync(previous.workspace).isDirectory()))throw Error('原执行目录已不可用，请重新设置后完整运行。');if((previous.skillStamp||'')!==getSkillStamp())throw Error('技能库已变化，请完整重跑。');if(previous.supplements?.length)throw Error('原任务包含中途补充，请将补充合入任务后完整运行。');const input=graph.nodes.find(n=>n.type==='input'),prefix=previous.task+'\n\n共享资料：',oldInput=previous.nodes[input?.id]?.text||'';const materials=previous.materials??(oldInput.startsWith(prefix)?oldInput.slice(prefix.length):'');const started=runner.run(graph,members,{task:previous.task,workspace:previous.workspace,materials,attachments:previous.attachments||[],skillStamp:getSkillStamp(),previous,from:nodeId,roomId,resume:true,resumeOnly:true});emit({type:'running',roomId});started.catch(e=>{emit({type:'workflowFailure',error:e.message});emit({type:'idle',roomId});});return true;}
  return {runner,handlers,startInRoom,retryInRoom,purgeRoomRuns};
}
module.exports={createWorkflows};
